var cityData = {
	"result": 1,
	"msg": "",
	"data": {
		"traffic": "0",
		"adsInfo": {
			"adspaceId": "1458",
			"sitelabel": "tracysite",
			"channellabel": "tracychannel",
			"adspacelabel": "1111",
			"type": "通栏广告",
			"size": "970*90",
			"position": "第一屏",
			"adfomat": ["jpg ", "gif ", "swf ", "png "],
			"price": "0.01",
			"seller": "tracy_seller"
		},
		"selected": [],
		"helper": [{
			"id": "CNBJ",
			"label": "北京",
			"level": "1"
		}, {
			"id": "CNTJ",
			"label": "天津",
			"level": "1"
		}, {
			"id": "CNHE",
			"label": "河北",
			"children": [{
				"id": "CNHESJ",
				"label": "石家庄",
				"level": "2",
				"children":[
					{"id":"wbzdsj1","label":"我编造1","level":0},
					{"id":"wbzdsj2","label":"我编造2","level":0},
					{"id":"wbzdsj3","label":"我编造3","level":0},
					{"id":"wbzdsj4","label":"我编造4","level":0},
					{"id":"wbzdsj5","label":"我编造5","level":0},
					{"id":"wbzdsj6","label":"我编造6","level":0}
				]
			}, {
				"id": "CNHETS",
				"label": "唐山",
				"level": "2"
			}, {
				"id": "CNHEQH",
				"label": "秦皇岛",
				"level": "0"
			}, {
				"id": "CNHEHD",
				"label": "邯郸",
				"level": "0"
			}, {
				"id": "CNHEXT",
				"label": "邢台",
				"level": "0"
			}, {
				"id": "CNHEBD",
				"label": "保定",
				"level": "0"
			}, {
				"id": "CNHEZJ",
				"label": "张家口",
				"level": "0"
			}, {
				"id": "CNHECD",
				"label": "承德",
				"level": "0"
			}, {
				"id": "CNHECZ",
				"label": "沧州",
				"level": "0"
			}, {
				"id": "CNHELF",
				"label": "廊坊",
				"level": "0"
			}, {
				"id": "CNHEHS",
				"label": "衡水",
				"level": "0"
			}]
		}, {
			"id": "CNSX",
			"label": "山西",
			"children": [{
				"id": "CNSXTY",
				"label": "太原",
				"level": "2"
			}, {
				"id": "CNSXDT",
				"label": "大同",
				"level": "0"
			}, {
				"id": "CNSXYQ",
				"label": "阳泉",
				"level": "0"
			}, {
				"id": "CNSXCZ",
				"label": "长治",
				"level": "0"
			}, {
				"id": "CNSXJC",
				"label": "晋城",
				"level": "0"
			}, {
				"id": "CNSXSZ",
				"label": "朔州",
				"level": "0"
			}, {
				"id": "CNSXJZ",
				"label": "晋中",
				"level": "0"
			}, {
				"id": "CNSXYC",
				"label": "运城",
				"level": "0"
			}, {
				"id": "CNSXQZ",
				"label": "忻州",
				"level": "0"
			}, {
				"id": "CNSXLF",
				"label": "临汾",
				"level": "0"
			}, {
				"id": "CNSXLL",
				"label": "吕梁",
				"level": "0"
			}]
		}, {
			"id": "CNNM",
			"label": "内蒙古",
			"children": [{
				"id": "CNNMHH",
				"label": "呼和浩特",
				"level": "0"
			}, {
				"id": "CNNMBT",
				"label": "包头",
				"level": "0"
			}, {
				"id": "CNNMWH",
				"label": "乌海",
				"level": "0"
			}, {
				"id": "CNNMCF",
				"label": "赤峰",
				"level": "0"
			}, {
				"id": "CNNMTL",
				"label": "通辽",
				"level": "0"
			}, {
				"id": "CNNMEE",
				"label": "鄂尔多斯",
				"level": "0"
			}, {
				"id": "CNNMHL",
				"label": "呼伦贝尔",
				"level": "0"
			}, {
				"id": "CNNMBY",
				"label": "巴彦淖尔",
				"level": "0"
			}, {
				"id": "CNNMWM",
				"label": "乌兰察布",
				"level": "0"
			}, {
				"id": "CNNMXA",
				"label": "兴安盟",
				"level": "0"
			}, {
				"id": "CNNMXL",
				"label": "锡林郭勒",
				"level": "0"
			}, {
				"id": "CNNMAL",
				"label": "阿拉善",
				"level": "0"
			}]
		}, {
			"id": "CNLN",
			"label": "辽宁",
			"children": [{
				"id": "CNLNSY",
				"label": "沈阳",
				"level": "2"
			}, {
				"id": "CNLNDL",
				"label": "大连",
				"level": "2"
			}, {
				"id": "CNLNAS",
				"label": "鞍山",
				"level": "0"
			}, {
				"id": "CNLNFS",
				"label": "抚顺",
				"level": "0"
			}, {
				"id": "CNLNBX",
				"label": "本溪",
				"level": "0"
			}, {
				"id": "CNLNDD",
				"label": "丹东",
				"level": "0"
			}, {
				"id": "CNLNJZ",
				"label": "锦州",
				"level": "0"
			}, {
				"id": "CNLNYK",
				"label": "营口",
				"level": "0"
			}, {
				"id": "CNLNFX",
				"label": "阜新",
				"level": "0"
			}, {
				"id": "CNLNLY",
				"label": "辽阳",
				"level": "0"
			}, {
				"id": "CNLNPJ",
				"label": "盘锦",
				"level": "0"
			}, {
				"id": "CNLNTL",
				"label": "铁岭",
				"level": "0"
			}, {
				"id": "CNLNCY",
				"label": "朝阳",
				"level": "0"
			}, {
				"id": "CNLNJX",
				"label": "葫芦岛",
				"level": "0"
			}]
		}, {
			"id": "CNJL",
			"label": "吉林",
			"children": [{
				"id": "CNJLCC",
				"label": "长春",
				"level": "2"
			}, {
				"id": "CNJLJL",
				"label": "吉林",
				"level": "0"
			}, {
				"id": "CNJLSP",
				"label": "四平",
				"level": "0"
			}, {
				"id": "CNJLLY",
				"label": "辽源",
				"level": "0"
			}, {
				"id": "CNJLTH",
				"label": "通化",
				"level": "0"
			}, {
				"id": "CNJLBS",
				"label": "白山",
				"level": "0"
			}, {
				"id": "CNJLSY",
				"label": "松原",
				"level": "0"
			}, {
				"id": "CNJLBC",
				"label": "白城",
				"level": "0"
			}, {
				"id": "CNJLYJ",
				"label": "延边",
				"level": "0"
			}]
		}, {
			"id": "CNHL",
			"label": "黑龙江",
			"children": [{
				"id": "CNHLHE",
				"label": "哈尔滨",
				"level": "2"
			}, {
				"id": "CNHLQQ",
				"label": "齐齐哈尔",
				"level": "0"
			}, {
				"id": "CNHLJX",
				"label": "鸡西",
				"level": "0"
			}, {
				"id": "CNHLHG",
				"label": "鹤岗",
				"level": "0"
			}, {
				"id": "CNHLSY",
				"label": "双鸭山",
				"level": "0"
			}, {
				"id": "CNHLDQ",
				"label": "大庆",
				"level": "0"
			}, {
				"id": "CNHLYC",
				"label": "伊春",
				"level": "0"
			}, {
				"id": "CNHLJM",
				"label": "佳木斯",
				"level": "0"
			}, {
				"id": "CNHLQT",
				"label": "七台河",
				"level": "0"
			}, {
				"id": "CNHLMD",
				"label": "牡丹江",
				"level": "0"
			}, {
				"id": "CNHLHH",
				"label": "黑河",
				"level": "0"
			}, {
				"id": "CNHLSH",
				"label": "绥化",
				"level": "0"
			}, {
				"id": "CNHLDX",
				"label": "大兴安岭",
				"level": "0"
			}]
		}, {
			"id": "CNSH",
			"label": "上海",
			"level": "1"
		}, {
			"id": "CNJS",
			"label": "江苏",
			"children": [{
				"id": "CNJSNJ",
				"label": "南京",
				"level": "2"
			}, {
				"id": "CNJSWX",
				"label": "无锡",
				"level": "2"
			}, {
				"id": "CNJSXZ",
				"label": "徐州",
				"level": "0"
			}, {
				"id": "CNJSCZ",
				"label": "常州",
				"level": "0"
			}, {
				"id": "CNJSSZ",
				"label": "苏州",
				"level": "2"
			}, {
				"id": "CNJSNT",
				"label": "南通",
				"level": "0"
			}, {
				"id": "CNJSLY",
				"label": "连云港",
				"level": "0"
			}, {
				"id": "CNJSHA",
				"label": "淮安",
				"level": "0"
			}, {
				"id": "CNJSYC",
				"label": "盐城",
				"level": "0"
			}, {
				"id": "CNJSYZ",
				"label": "扬州",
				"level": "0"
			}, {
				"id": "CNJSZJ",
				"label": "镇江",
				"level": "0"
			}, {
				"id": "CNJSTZ",
				"label": "泰州",
				"level": "0"
			}, {
				"id": "CNJSSQ",
				"label": "宿迁",
				"level": "0"
			}]
		}, {
			"id": "CNZJ",
			"label": "浙江",
			"children": [{
				"id": "CNZJHZ",
				"label": "杭州",
				"level": "2"
			}, {
				"id": "CNZJNB",
				"label": "宁波",
				"level": "2"
			}, {
				"id": "CNZJWZ",
				"label": "温州",
				"level": "2"
			}, {
				"id": "CNZJJX",
				"label": "嘉兴",
				"level": "0"
			}, {
				"id": "CNZJHU",
				"label": "湖州",
				"level": "0"
			}, {
				"id": "CNZJSX",
				"label": "绍兴",
				"level": "0"
			}, {
				"id": "CNZJJH",
				"label": "金华",
				"level": "0"
			}, {
				"id": "CNZJQZ",
				"label": "衢州",
				"level": "0"
			}, {
				"id": "CNZJZS",
				"label": "舟山",
				"level": "0"
			}, {
				"id": "CNZJTZ",
				"label": "台州",
				"level": "0"
			}, {
				"id": "CNZJLS",
				"label": "丽水",
				"level": "0"
			}]
		}, {
			"id": "CNAH",
			"label": "安徽",
			"children": [{
				"id": "CNAHHF",
				"label": "合肥",
				"level": "2"
			}, {
				"id": "CNAHWH",
				"label": "芜湖",
				"level": "0"
			}, {
				"id": "CNAHBB",
				"label": "蚌埠",
				"level": "0"
			}, {
				"id": "CNAHHN",
				"label": "淮南",
				"level": "0"
			}, {
				"id": "CNAHMA",
				"label": "马鞍山",
				"level": "0"
			}, {
				"id": "CNAHHB",
				"label": "淮北",
				"level": "0"
			}, {
				"id": "CNAHTL",
				"label": "铜陵",
				"level": "0"
			}, {
				"id": "CNAHAQ",
				"label": "安庆",
				"level": "0"
			}, {
				"id": "CNAHHS",
				"label": "黄山",
				"level": "0"
			}, {
				"id": "CNAHCZ",
				"label": "滁州",
				"level": "0"
			}, {
				"id": "CNAHFY",
				"label": "阜阳",
				"level": "0"
			}, {
				"id": "CNAHSZ",
				"label": "宿州",
				"level": "0"
			}, {
				"id": "CNAHCH",
				"label": "巢湖",
				"level": "0"
			}, {
				"id": "CNAHLA",
				"label": "六安",
				"level": "0"
			}, {
				"id": "CNAHHZ",
				"label": "亳州",
				"level": "0"
			}, {
				"id": "CNAHCO",
				"label": "池州",
				"level": "0"
			}, {
				"id": "CNAHXC",
				"label": "宣城",
				"level": "0"
			}]
		}, {
			"id": "CNFJ",
			"label": "福建",
			"children": [{
				"id": "CNFJFZ",
				"label": "福州",
				"level": "2"
			}, {
				"id": "CNFJXM",
				"label": "厦门",
				"level": "2"
			}, {
				"id": "CNFJPT",
				"label": "莆田",
				"level": "0"
			}, {
				"id": "CNFJSM",
				"label": "三明",
				"level": "0"
			}, {
				"id": "CNFJQZ",
				"label": "泉州",
				"level": "0"
			}, {
				"id": "CNFJZZ",
				"label": "漳州",
				"level": "0"
			}, {
				"id": "CNFJNP",
				"label": "南平",
				"level": "0"
			}, {
				"id": "CNFJLY",
				"label": "龙岩",
				"level": "0"
			}, {
				"id": "CNFJND",
				"label": "宁德",
				"level": "0"
			}]
		}, {
			"id": "CNJX",
			"label": "江西",
			"children": [{
				"id": "CNJXNC",
				"label": "南昌",
				"level": "2"
			}, {
				"id": "CNJXJD",
				"label": "景德镇",
				"level": "0"
			}, {
				"id": "CNJXPX",
				"label": "萍乡",
				"level": "0"
			}, {
				"id": "CNJXJJ",
				"label": "九江",
				"level": "0"
			}, {
				"id": "CNJXXY",
				"label": "新余",
				"level": "0"
			}, {
				"id": "CNJXYT",
				"label": "鹰潭",
				"level": "0"
			}, {
				"id": "CNJXGZ",
				"label": "赣州",
				"level": "0"
			}, {
				"id": "CNJXJA",
				"label": "吉安",
				"level": "0"
			}, {
				"id": "CNJXYC",
				"label": "宜春",
				"level": "0"
			}, {
				"id": "CNJXFZ",
				"label": "抚州",
				"level": "0"
			}, {
				"id": "CNJXSR",
				"label": "上饶",
				"level": "0"
			}]
		}, {
			"id": "CNSD",
			"label": "山东",
			"children": [{
				"id": "CNSDJN",
				"label": "济南",
				"level": "2"
			}, {
				"id": "CNSDQD",
				"label": "青岛",
				"level": "2"
			}, {
				"id": "CNSDZB",
				"label": "淄博",
				"level": "2"
			}, {
				"id": "CNSDZZ",
				"label": "枣庄",
				"level": "0"
			}, {
				"id": "CNSDDY",
				"label": "东营",
				"level": "0"
			}, {
				"id": "CNSDYT",
				"label": "烟台",
				"level": "2"
			}, {
				"id": "CNSDWF",
				"label": "潍坊",
				"level": "0"
			}, {
				"id": "CNSDJI",
				"label": "济宁",
				"level": "0"
			}, {
				"id": "CNSDTA",
				"label": "泰安",
				"level": "0"
			}, {
				"id": "CNSDWH",
				"label": "威海",
				"level": "0"
			}, {
				"id": "CNSDRZ",
				"label": "日照",
				"level": "0"
			}, {
				"id": "CNSDLW",
				"label": "莱芜",
				"level": "0"
			}, {
				"id": "CNSDLY",
				"label": "临沂",
				"level": "0"
			}, {
				"id": "CNSDDZ",
				"label": "德州",
				"level": "0"
			}, {
				"id": "CNSDLC",
				"label": "聊城",
				"level": "0"
			}, {
				"id": "CNSDBZ",
				"label": "滨州",
				"level": "0"
			}, {
				"id": "CNSDHZ",
				"label": "菏泽",
				"level": "0"
			}]
		}, {
			"id": "CNHA",
			"label": "河南",
			"children": [{
				"id": "CNHAZZ",
				"label": "郑州",
				"level": "2"
			}, {
				"id": "CNHAKF",
				"label": "开封",
				"level": "0"
			}, {
				"id": "CNHALY",
				"label": "洛阳",
				"level": "0"
			}, {
				"id": "CNHAPD",
				"label": "平顶山",
				"level": "0"
			}, {
				"id": "CNHAAY",
				"label": "安阳",
				"level": "0"
			}, {
				"id": "CNHAHB",
				"label": "鹤壁",
				"level": "0"
			}, {
				"id": "CNHAXX",
				"label": "新乡",
				"level": "0"
			}, {
				"id": "CNHAJZ",
				"label": "焦作",
				"level": "0"
			}, {
				"id": "CNHAPY",
				"label": "濮阳",
				"level": "0"
			}, {
				"id": "CNHAXC",
				"label": "许昌",
				"level": "0"
			}, {
				"id": "CNHALH",
				"label": "漯河",
				"level": "0"
			}, {
				"id": "CNHASM",
				"label": "三门峡",
				"level": "0"
			}, {
				"id": "CNHANY",
				"label": "南阳",
				"level": "0"
			}, {
				"id": "CNHASQ",
				"label": "商丘",
				"level": "0"
			}, {
				"id": "CNHAXY",
				"label": "信阳",
				"level": "0"
			}, {
				"id": "CNHAZK",
				"label": "周口",
				"level": "0"
			}, {
				"id": "CNHAZM",
				"label": "驻马店",
				"level": "0"
			}]
		}, {
			"id": "CNHB",
			"label": "湖北",
			"children": [{
				"id": "CNHBWH",
				"label": "武汉",
				"level": "2"
			}, {
				"id": "CNHBHS",
				"label": "黄石",
				"level": "0"
			}, {
				"id": "CNHBSY",
				"label": "十堰",
				"level": "0"
			}, {
				"id": "CNHBYC",
				"label": "宜昌",
				"level": "0"
			}, {
				"id": "CNHBXF",
				"label": "襄樊",
				"level": "0"
			}, {
				"id": "CNHBEZ",
				"label": "鄂州",
				"level": "0"
			}, {
				"id": "CNHBJM",
				"label": "荆门",
				"level": "0"
			}, {
				"id": "CNHBXG",
				"label": "孝感",
				"level": "0"
			}, {
				"id": "CNHBJZ",
				"label": "荆州",
				"level": "0"
			}, {
				"id": "CNHBHG",
				"label": "黄冈",
				"level": "0"
			}, {
				"id": "CNHBXN",
				"label": "咸宁",
				"level": "0"
			}, {
				"id": "CNHBSZ",
				"label": "随州",
				"level": "0"
			}, {
				"id": "CNHBES",
				"label": "恩施",
				"level": "0"
			}]
		}, {
			"id": "CNHN",
			"label": "湖南",
			"children": [{
				"id": "CNHNCS",
				"label": "长沙",
				"level": "2"
			}, {
				"id": "CNHNZZ",
				"label": "株洲",
				"level": "0"
			}, {
				"id": "CNHNXT",
				"label": "湘潭",
				"level": "0"
			}, {
				"id": "CNHNHY",
				"label": "衡阳",
				"level": "0"
			}, {
				"id": "CNHNSY",
				"label": "邵阳",
				"level": "0"
			}, {
				"id": "CNHNYY",
				"label": "岳阳",
				"level": "0"
			}, {
				"id": "CNHNCD",
				"label": "常德",
				"level": "0"
			}, {
				"id": "CNHNZJ",
				"label": "张家界",
				"level": "0"
			}, {
				"id": "CNHNIY",
				"label": "益阳",
				"level": "0"
			}, {
				"id": "CNHNCZ",
				"label": "郴州",
				"level": "0"
			}, {
				"id": "CNHNYZ",
				"label": "永州",
				"level": "0"
			}, {
				"id": "CNHNHH",
				"label": "怀化",
				"level": "0"
			}, {
				"id": "CNHNLD",
				"label": "娄底",
				"level": "0"
			}, {
				"id": "CNHNXX",
				"label": "湘西土家族苗族自治州",
				"level": "0"
			}]
		}, {
			"id": "CNGD",
			"label": "广东",
			"children": [{
				"id": "CNGDGZ",
				"label": "广州",
				"level": "1"
			}, {
				"id": "CNGDSG",
				"label": "韶关",
				"level": "0"
			}, {
				"id": "CNGDSZ",
				"label": "深圳",
				"level": "1"
			}, {
				"id": "CNGDZH",
				"label": "珠海",
				"level": "0"
			}, {
				"id": "CNGDST",
				"label": "汕头",
				"level": "0"
			}, {
				"id": "CNGDFS",
				"label": "佛山",
				"level": "2"
			}, {
				"id": "CNGDJM",
				"label": "江门",
				"level": "0"
			}, {
				"id": "CNGDZJ",
				"label": "湛江",
				"level": "0"
			}, {
				"id": "CNGDMM",
				"label": "茂名",
				"level": "0"
			}, {
				"id": "CNGDZQ",
				"label": "肇庆",
				"level": "0"
			}, {
				"id": "CNGDHZ",
				"label": "惠州",
				"level": "0"
			}, {
				"id": "CNGDMZ",
				"label": "梅州",
				"level": "0"
			}, {
				"id": "CNGDSW",
				"label": "汕尾",
				"level": "0"
			}, {
				"id": "CNGDHY",
				"label": "河源",
				"level": "0"
			}, {
				"id": "CNGDYJ",
				"label": "阳江",
				"level": "0"
			}, {
				"id": "CNGDQY",
				"label": "清远",
				"level": "0"
			}, {
				"id": "CNGDDG",
				"label": "东莞",
				"level": "2"
			}, {
				"id": "CNGDZS",
				"label": "中山",
				"level": "0"
			}, {
				"id": "CNGDCZ",
				"label": "潮州",
				"level": "0"
			}, {
				"id": "CNGDJY",
				"label": "揭阳",
				"level": "0"
			}, {
				"id": "CNGDYF",
				"label": "云浮",
				"level": "0"
			}]
		}, {
			"id": "CNGX",
			"label": "广西",
			"children": [{
				"id": "CNGXNN",
				"label": "南宁",
				"level": "2"
			}, {
				"id": "CNGXLZ",
				"label": "柳州",
				"level": "0"
			}, {
				"id": "CNGXGL",
				"label": "桂林",
				"level": "0"
			}, {
				"id": "CNGXWZ",
				"label": "梧州",
				"level": "0"
			}, {
				"id": "CNGXBH",
				"label": "北海",
				"level": "0"
			}, {
				"id": "CNGXFC",
				"label": "防城港",
				"level": "0"
			}, {
				"id": "CNGXQZ",
				"label": "钦州",
				"level": "0"
			}, {
				"id": "CNGXGG",
				"label": "贵港",
				"level": "0"
			}, {
				"id": "CNGXYL",
				"label": "玉林",
				"level": "0"
			}, {
				"id": "CNGXBS",
				"label": "百色",
				"level": "0"
			}, {
				"id": "CNGXHZ",
				"label": "贺州",
				"level": "0"
			}, {
				"id": "CNGXHC",
				"label": "河池",
				"level": "0"
			}, {
				"id": "CNGXLB",
				"label": "来宾",
				"level": "0"
			}, {
				"id": "CNGXCZ",
				"label": "崇左",
				"level": "0"
			}]
		}, {
			"id": "CNHI",
			"label": "海南",
			"children": [{
				"id": "CNHIHK",
				"label": "海口",
				"level": "0"
			}, {
				"id": "CNHISY",
				"label": "三亚",
				"level": "0"
			}]
		}, {
			"id": "CNCQ",
			"label": "重庆",
			"level": "2"
		}, {
			"id": "CNSC",
			"label": "四川",
			"children": [{
				"id": "CNSCCD",
				"label": "成都",
				"level": "2"
			}, {
				"id": "CNSCZG",
				"label": "自贡",
				"level": "0"
			}, {
				"id": "CNSCPZ",
				"label": "攀枝花",
				"level": "0"
			}, {
				"id": "CNSCLZ",
				"label": "泸州",
				"level": "0"
			}, {
				"id": "CNSCDY",
				"label": "德阳",
				"level": "0"
			}, {
				"id": "CNSCMY",
				"label": "绵阳",
				"level": "0"
			}, {
				"id": "CNSCGY",
				"label": "广元",
				"level": "0"
			}, {
				"id": "CNSCSN",
				"label": "遂宁",
				"level": "0"
			}, {
				"id": "CNSCNJ",
				"label": "内江",
				"level": "0"
			}, {
				"id": "CNSCLS",
				"label": "乐山",
				"level": "0"
			}, {
				"id": "CNSCNC",
				"label": "南充",
				"level": "0"
			}, {
				"id": "CNSCMS",
				"label": "眉山",
				"level": "0"
			}, {
				"id": "CNSCYB",
				"label": "宜宾",
				"level": "0"
			}, {
				"id": "CNSCGA",
				"label": "广安",
				"level": "0"
			}, {
				"id": "CNSCDZ",
				"label": "达州",
				"level": "0"
			}, {
				"id": "CNSCYA",
				"label": "雅安",
				"level": "0"
			}, {
				"id": "CNSCBZ",
				"label": "巴中",
				"level": "0"
			}, {
				"id": "CNSCZY",
				"label": "资阳",
				"level": "0"
			}, {
				"id": "CNSCAB",
				"label": "阿坝",
				"level": "0"
			}, {
				"id": "CNSCGZ",
				"label": "甘孜藏族自治州",
				"level": "0"
			}, {
				"id": "CNSCXC",
				"label": "凉山彝族自治州",
				"level": "0"
			}]
		}, {
			"id": "CNGZ",
			"label": "贵州",
			"children": [{
				"id": "CNGZGY",
				"label": "贵阳",
				"level": "0"
			}, {
				"id": "CNGZLP",
				"label": "六盘水",
				"level": "0"
			}, {
				"id": "CNGZZY",
				"label": "遵义",
				"level": "0"
			}, {
				"id": "CNGZAS",
				"label": "安顺",
				"level": "0"
			}, {
				"id": "CNGZTR",
				"label": "铜仁",
				"level": "0"
			}, {
				"id": "CNGZQX",
				"label": "黔西南布依族苗族自治州",
				"level": "0"
			}, {
				"id": "CNGZBJ",
				"label": "毕节",
				"level": "0"
			}, {
				"id": "CNGZQD",
				"label": "黔东南苗族侗族自治州",
				"level": "0"
			}, {
				"id": "CNGZQN",
				"label": "黔南布依族苗族自治州",
				"level": "0"
			}]
		}, {
			"id": "CNYN",
			"label": "云南",
			"children": [{
				"id": "CNYNKM",
				"label": "昆明",
				"level": "2"
			}, {
				"id": "CNYNQJ",
				"label": "曲靖",
				"level": "0"
			}, {
				"id": "CNYNYX",
				"label": "玉溪",
				"level": "0"
			}, {
				"id": "CNYNBS",
				"label": "保山",
				"level": "0"
			}, {
				"id": "CNYNZT",
				"label": "昭通",
				"level": "0"
			}, {
				"id": "CNYNLJ",
				"label": "丽江",
				"level": "0"
			}, {
				"id": "CNYNSM",
				"label": "普洱市",
				"level": "0"
			}, {
				"id": "CNYNLC",
				"label": "临沧",
				"level": "0"
			}, {
				"id": "CNYNCX",
				"label": "楚雄",
				"level": "0"
			}, {
				"id": "CNYNHH",
				"label": "红河哈尼族彝族自治州",
				"level": "0"
			}, {
				"id": "CNYNWS",
				"label": "文山",
				"level": "0"
			}, {
				"id": "CNYNXS",
				"label": "西双版纳",
				"level": "0"
			}, {
				"id": "CNYNDL",
				"label": "大理",
				"level": "0"
			}, {
				"id": "CNYNDH",
				"label": "德宏傣族景颇族自治州",
				"level": "0"
			}, {
				"id": "CNYNNJ",
				"label": "怒江",
				"level": "0"
			}, {
				"id": "CNYNDQ",
				"label": "迪庆",
				"level": "0"
			}]
		}, {
			"id": "CNXZ",
			"label": "西藏",
			"children": [{
				"id": "CNXZLS",
				"label": "拉萨",
				"level": "0"
			}, {
				"id": "CNXZCD",
				"label": "昌都",
				"level": "0"
			}, {
				"id": "CNXZSN",
				"label": "山南",
				"level": "0"
			}, {
				"id": "CNXZRG",
				"label": "日喀则",
				"level": "0"
			}, {
				"id": "CNXZNQ",
				"label": "那曲",
				"level": "0"
			}, {
				"id": "CNXZAL",
				"label": "阿里",
				"level": "0"
			}, {
				"id": "CNXZLZ",
				"label": "林芝",
				"level": "0"
			}]
		}, {
			"id": "CNXA",
			"label": "陕西",
			"children": [{
				"id": "CNXAXA",
				"label": "西安",
				"level": "2"
			}, {
				"id": "CNXATC",
				"label": "铜川",
				"level": "0"
			}, {
				"id": "CNXABJ",
				"label": "宝鸡",
				"level": "0"
			}, {
				"id": "CNXAXY",
				"label": "咸阳",
				"level": "0"
			}, {
				"id": "CNXAWN",
				"label": "渭南",
				"level": "0"
			}, {
				"id": "CNXAYA",
				"label": "延安",
				"level": "0"
			}, {
				"id": "CNXAHZ",
				"label": "汉中",
				"level": "0"
			}, {
				"id": "CNXAYL",
				"label": "榆林",
				"level": "0"
			}, {
				"id": "CNXAAK",
				"label": "安康",
				"level": "0"
			}, {
				"id": "CNXASL",
				"label": "商洛",
				"level": "0"
			}]
		}, {
			"id": "CNGS",
			"label": "甘肃",
			"children": [{
				"id": "CNGSLZ",
				"label": "兰州",
				"level": "0"
			}, {
				"id": "CNGSJY",
				"label": "嘉峪关",
				"level": "0"
			}, {
				"id": "CNGSJC",
				"label": "金昌市",
				"level": "0"
			}, {
				"id": "CNGSBY",
				"label": "白银市",
				"level": "0"
			}, {
				"id": "CNGSTS",
				"label": "天水",
				"level": "0"
			}, {
				"id": "CNGSWW",
				"label": "武威",
				"level": "0"
			}, {
				"id": "CNGSZY",
				"label": "张掖",
				"level": "0"
			}, {
				"id": "CNGSPL",
				"label": "平凉",
				"level": "0"
			}, {
				"id": "CNGSJQ",
				"label": "酒泉",
				"level": "0"
			}, {
				"id": "CNGSQY",
				"label": "庆阳",
				"level": "0"
			}, {
				"id": "CNGSDX",
				"label": "定西",
				"level": "0"
			}, {
				"id": "CNGSLN",
				"label": "陇南",
				"level": "0"
			}, {
				"id": "CNGSLX",
				"label": "临夏回族自治州",
				"level": "0"
			}, {
				"id": "CNGSGN",
				"label": "甘南藏族自治州",
				"level": "0"
			}]
		}, {
			"id": "CNQH",
			"label": "青海",
			"children": [{
				"id": "CNQHXN",
				"label": "西宁",
				"level": "0"
			}, {
				"id": "CNQHHD",
				"label": "海东",
				"level": "0"
			}, {
				"id": "CNQHHB",
				"label": "海北",
				"level": "0"
			}, {
				"id": "CNQHHH",
				"label": "黄南",
				"level": "0"
			}, {
				"id": "CNQHHN",
				"label": "海南",
				"level": "0"
			}, {
				"id": "CNQHGL",
				"label": "果洛",
				"level": "0"
			}, {
				"id": "CNQHYS",
				"label": "玉树",
				"level": "0"
			}, {
				"id": "CNQHHX",
				"label": "海西",
				"level": "0"
			}]
		}, {
			"id": "CNNX",
			"label": "宁夏",
			"children": [{
				"id": "CNNXYC",
				"label": "银川",
				"level": "0"
			}, {
				"id": "CNNXSZ",
				"label": "石嘴山",
				"level": "0"
			}, {
				"id": "CNNXWZ",
				"label": "吴忠",
				"level": "0"
			}, {
				"id": "CNNXGY",
				"label": "固原",
				"level": "0"
			}, {
				"id": "CNNXZW",
				"label": "中卫",
				"level": "0"
			}]
		}, {
			"id": "CNXJ",
			"label": "新疆",
			"children": [{
				"id": "CNXJWL",
				"label": "乌鲁木齐",
				"level": "0"
			}, {
				"id": "CNXJKL",
				"label": "克拉玛依",
				"level": "0"
			}, {
				"id": "CNXJTL",
				"label": "吐鲁番",
				"level": "0"
			}, {
				"id": "CNXJHM",
				"label": "哈密",
				"level": "0"
			}, {
				"id": "CNXJCJ",
				"label": "昌吉",
				"level": "0"
			}, {
				"id": "CNXJBE",
				"label": "博尔塔拉蒙古自治州",
				"level": "0"
			}, {
				"id": "CNXJBY",
				"label": "巴音",
				"level": "0"
			}, {
				"id": "CNXJEK",
				"label": "阿克苏",
				"level": "0"
			}, {
				"id": "CNXJKE",
				"label": "克孜勒苏柯尔克孜自治州",
				"level": "0"
			}, {
				"id": "CNXJKS",
				"label": "喀什",
				"level": "0"
			}, {
				"id": "CNXJHT",
				"label": "和田",
				"level": "0"
			}, {
				"id": "CNXJYL",
				"label": "伊犁哈萨克自治州",
				"level": "0"
			}, {
				"id": "CNXJTC",
				"label": "塔城",
				"level": "0"
			}, {
				"id": "CNXJAL",
				"label": "阿勒泰",
				"level": "0"
			}]
		}, {
			"id": "CNHK",
			"label": "香港",
			"level": "0"
		}, {
			"id": "CNMO",
			"label": "澳门",
			"level": "0"
		}, {
			"id": "CNTW",
			"label": "台湾",
			"level": "0"
		}]
	}
};


