var data = {
    "cityOwnerShip": {
        "CNAH00": ["CNAHAQ", "CNAHBB", "CNAHCH", "CNAHCO", "CNAHCZ", "CNAHFY", "CNAHHB", "CNAHHF", "CNAHHN", "CNAHHS", "CNAHHZ", "CNAHLA", "CNAHMA", "CNAHSZ", "CNAHTL", "CNAHWH", "CNAHXC"],
        "CNFJ00": ["CNFJFZ", "CNFJLY", "CNFJND", "CNFJNP", "CNFJPT", "CNFJQZ", "CNFJSM", "CNFJXM", "CNFJZZ"],
        "CNGD00": ["CNGDCZ", "CNGDDG", "CNGDFS", "CNGDGZ", "CNGDHY", "CNGDHZ", "CNGDJM", "CNGDJY", "CNGDMM", "CNGDMZ", "CNGDQY", "CNGDSG", "CNGDST", "CNGDSW", "CNGDSZ", "CNGDYF", "CNGDYJ", "CNGDZH", "CNGDZJ", "CNGDZQ", "CNGDZS"],
        "CNGS00": ["CNGSBY", "CNGSDX", "CNGSGN", "CNGSJC", "CNGSJQ", "CNGSJY", "CNGSLN", "CNGSLX", "CNGSLZ", "CNGSPL", "CNGSQY", "CNGSTS", "CNGSWW", "CNGSZY"],
        "CNGX00": ["CNGXBH", "CNGXBS", "CNGXCZ", "CNGXFC", "CNGXGG", "CNGXGL", "CNGXHC", "CNGXHZ", "CNGXLB", "CNGXLZ", "CNGXNN", "CNGXQZ", "CNGXWZ", "CNGXYL"],
        "CNGZ00": ["CNGZAS", "CNGZBJ", "CNGZGY", "CNGZLP", "CNGZQD", "CNGZQN", "CNGZQX", "CNGZTR", "CNGZZY"],
        "CNHA00": ["CNHA90", "CNHAAY", "CNHAHB", "CNHAJZ", "CNHAKF", "CNHALH", "CNHALY", "CNHANY", "CNHAPD", "CNHAPY", "CNHASM", "CNHASQ", "CNHAXC", "CNHAXX", "CNHAXY", "CNHAZK", "CNHAZM", "CNHAZZ"],
        "CNHB00": ["CNHB90", "CNHBES", "CNHBEZ", "CNHBHG", "CNHBHS", "CNHBJM", "CNHBJZ", "CNHBSY", "CNHBSZ", "CNHBWH", "CNHBXF", "CNHBXG", "CNHBXN", "CNHBYC"],
        "CNHE00": ["CNHEBD", "CNHECD", "CNHECZ", "CNHEHD", "CNHEHS", "CNHELF", "CNHEQH", "CNHESJ", "CNHETS", "CNHEXT", "CNHEZJ"],
        "CNHI00": ["CNHI90", "CNHIHK", "CNHISY"],
        "CNHL00": ["CNHLDQ", "CNHLDX", "CNHLHE", "CNHLHG", "CNHLHH", "CNHLJM", "CNHLJX", "CNHLMD", "CNHLQQ", "CNHLQT", "CNHLSH", "CNHLSY", "CNHLYC"],
        "CNHN00": ["CNHNCD", "CNHNCS", "CNHNCZ", "CNHNHH", "CNHNHY", "CNHNIY", "CNHNLD", "CNHNSY", "CNHNXT", "CNHNXX", "CNHNYY", "CNHNYZ", "CNHNZJ", "CNHNZZ"],
        "CNJL00": ["CNJLBC", "CNJLBS", "CNJLCC", "CNJLJL", "CNJLLY", "CNJLSP", "CNJLSY", "CNJLTH", "CNJLYJ"],
        "CNJS00": ["CNJSCZ", "CNJSHA", "CNJSLY", "CNJSNJ", "CNJSNT", "CNJSSQ", "CNJSSZ", "CNJSTZ", "CNJSWX", "CNJSXZ", "CNJSYC", "CNJSYZ", "CNJSZJ"],
        "CNJX00": ["CNJXFZ", "CNJXGZ", "CNJXJA", "CNJXJD", "CNJXJJ", "CNJXNC", "CNJXPX", "CNJXSR", "CNJXXY", "CNJXYC", "CNJXYT"],
        "CNLN00": ["CNLNAS", "CNLNBX", "CNLNCY", "CNLNDD", "CNLNDL", "CNLNFS", "CNLNFX", "CNLNJX", "CNLNJZ", "CNLNLY", "CNLNPJ", "CNLNSY", "CNLNTL", "CNLNYK"],
        "CNNM00": ["CNNMAL", "CNNMBT", "CNNMBY", "CNNMCF", "CNNMEE", "CNNMHH", "CNNMHL", "CNNMTL", "CNNMWH", "CNNMWM", "CNNMXA", "CNNMXL"],
        "CNNX00": ["CNNXGY", "CNNXSZ", "CNNXWZ", "CNNXYC", "CNNXZW"],
        "CNQH00": ["CNQHGL", "CNQHHB", "CNQHHD", "CNQHHH", "CNQHHN", "CNQHHX", "CNQHXN", "CNQHYS"],
        "CNSC00": ["CNSCAB", "CNSCBZ", "CNSCCD", "CNSCDY", "CNSCDZ", "CNSCGA", "CNSCGY", "CNSCGZ", "CNSCLS", "CNSCLZ", "CNSCMS", "CNSCMY", "CNSCNC", "CNSCNJ", "CNSCPZ", "CNSCSN", "CNSCXC", "CNSCYA", "CNSCYB", "CNSCZG", "CNSCZY"],
        "CNSD00": ["CNSDBZ", "CNSDDY", "CNSDDZ", "CNSDHZ", "CNSDJI", "CNSDJN", "CNSDLC", "CNSDLW", "CNSDLY", "CNSDQD", "CNSDRZ", "CNSDTA", "CNSDWF", "CNSDWH", "CNSDYT", "CNSDZB", "CNSDZZ"],
        "CNSX00": ["CNSXCZ", "CNSXDT", "CNSXJC", "CNSXJZ", "CNSXLF", "CNSXLL", "CNSXQZ", "CNSXSZ", "CNSXTY", "CNSXYC", "CNSXYQ"],
        "CNXA00": ["CNXAAK", "CNXABJ", "CNXAHZ", "CNXASL", "CNXATC", "CNXAWN", "CNXAXA", "CNXAXY", "CNXAYA", "CNXAYL"],
        "CNXJ00": ["CNXJ90", "CNXJAL", "CNXJBE", "CNXJBY", "CNXJCJ", "CNXJEK", "CNXJHM", "CNXJHT", "CNXJKE", "CNXJKL", "CNXJKS", "CNXJTC", "CNXJTL", "CNXJWL", "CNXJYL"],
        "CNXZ00": ["CNXZAL", "CNXZCD", "CNXZLS", "CNXZLZ", "CNXZNQ", "CNXZRG", "CNXZSN"],
        "CNYN00": ["CNYNBS", "CNYNCX", "CNYNDH", "CNYNDL", "CNYNDQ", "CNYNHH", "CNYNKM", "CNYNLC", "CNYNLJ", "CNYNNJ", "CNYNQJ", "CNYNSM", "CNYNWS", "CNYNXS", "CNYNYX", "CNYNZT"],
        "CNZJ00": ["CNZJHU", "CNZJHZ", "CNZJJH", "CNZJJX", "CNZJLS", "CNZJNB", "CNZJQZ", "CNZJSX", "CNZJTZ", "CNZJWZ", "CNZJZS"]
    },
    "the1cities": [{
        "i": "CNAH00",
        "t": "安徽"
    }, {
        "i": "CNBJ00",
        "t": "北京"
    }, {
        "i": "CNCQ00",
        "t": "重庆"
    }, {
        "i": "CNFJ00",
        "t": "福建"
    }, {
        "i": "CNGD00",
        "t": "广东"
    }, {
        "i": "CNGS00",
        "t": "甘肃"
    }, {
        "i": "CNGX00",
        "t": "广西"
    }, {
        "i": "CNGZ00",
        "t": "贵州"
    }, {
        "i": "CNHA00",
        "t": "河南"
    }, {
        "i": "CNHB00",
        "t": "湖北"
    }, {
        "i": "CNHE00",
        "t": "河北"
    }, {
        "i": "CNHI00",
        "t": "海南"
    }, {
        "i": "CNHK00",
        "t": "香港"
    }, {
        "i": "CNHL00",
        "t": "黑龙江"
    }, {
        "i": "CNHN00",
        "t": "湖南"
    }, {
        "i": "CNJL00",
        "t": "吉林"
    }, {
        "i": "CNJS00",
        "t": "江苏"
    }, {
        "i": "CNJX00",
        "t": "江西"
    }, {
        "i": "CNLN00",
        "t": "辽宁"
    }, {
        "i": "CNMO00",
        "t": "澳门"
    }, {
        "i": "CNNM00",
        "t": "内蒙古"
    }, {
        "i": "CNNX00",
        "t": "宁夏"
    }, {
        "i": "CNQH00",
        "t": "青海"
    }, {
        "i": "CNSC00",
        "t": "四川"
    }, {
        "i": "CNSD00",
        "t": "山东"
    }, {
        "i": "CNSH00",
        "t": "上海"
    }, {
        "i": "CNSX00",
        "t": "山西"
    }, {
        "i": "CNTJ00",
        "t": "天津"
    }, {
        "i": "CNTW00",
        "t": "台湾"
    }, {
        "i": "CNXA00",
        "t": "陕西"
    }, {
        "i": "CNXJ00",
        "t": "新疆"
    }, {
        "i": "CNXZ00",
        "t": "西藏"
    }, {
        "i": "CNYN00",
        "t": "云南"
    }, {
        "i": "CNZJ00",
        "t": "浙江"
    }],
    "the2cities": [{
        "i": "CNAHAQ",
        "t": "安庆"
    }, {
        "i": "CNAHBB",
        "t": "蚌埠"
    }, {
        "i": "CNAHCH",
        "t": "巢湖"
    }, {
        "i": "CNAHCO",
        "t": "池州"
    }, {
        "i": "CNAHCZ",
        "t": "滁州"
    }, {
        "i": "CNAHFY",
        "t": "阜阳"
    }, {
        "i": "CNAHHB",
        "t": "淮北"
    }, {
        "i": "CNAHHF",
        "t": "合肥"
    }, {
        "i": "CNAHHN",
        "t": "淮南"
    }, {
        "i": "CNAHHS",
        "t": "黄山"
    }, {
        "i": "CNAHHZ",
        "t": "亳州"
    }, {
        "i": "CNAHLA",
        "t": "六安"
    }, {
        "i": "CNAHMA",
        "t": "马鞍山"
    }, {
        "i": "CNAHSZ",
        "t": "宿州"
    }, {
        "i": "CNAHTL",
        "t": "铜陵"
    }, {
        "i": "CNAHWH",
        "t": "芜湖"
    }, {
        "i": "CNAHXC",
        "t": "宣城"
    }, {
        "i": "CNFJFZ",
        "t": "福州"
    }, {
        "i": "CNFJLY",
        "t": "龙岩"
    }, {
        "i": "CNFJND",
        "t": "宁德"
    }, {
        "i": "CNFJNP",
        "t": "南平"
    }, {
        "i": "CNFJPT",
        "t": "莆田"
    }, {
        "i": "CNFJQZ",
        "t": "泉州"
    }, {
        "i": "CNFJSM",
        "t": "三明"
    }, {
        "i": "CNFJXM",
        "t": "厦门"
    }, {
        "i": "CNFJZZ",
        "t": "漳州"
    }, {
        "i": "CNGDCZ",
        "t": "潮州"
    }, {
        "i": "CNGDDG",
        "t": "东莞"
    }, {
        "i": "CNGDFS",
        "t": "佛山"
    }, {
        "i": "CNGDGZ",
        "t": "广州"
    }, {
        "i": "CNGDHY",
        "t": "河源"
    }, {
        "i": "CNGDHZ",
        "t": "惠州"
    }, {
        "i": "CNGDJM",
        "t": "江门"
    }, {
        "i": "CNGDJY",
        "t": "揭阳"
    }, {
        "i": "CNGDMM",
        "t": "茂名"
    }, {
        "i": "CNGDMZ",
        "t": "梅州"
    }, {
        "i": "CNGDQY",
        "t": "清远"
    }, {
        "i": "CNGDSG",
        "t": "韶关"
    }, {
        "i": "CNGDST",
        "t": "汕头"
    }, {
        "i": "CNGDSW",
        "t": "汕尾"
    }, {
        "i": "CNGDSZ",
        "t": "深圳"
    }, {
        "i": "CNGDYF",
        "t": "云浮"
    }, {
        "i": "CNGDYJ",
        "t": "阳江"
    }, {
        "i": "CNGDZH",
        "t": "珠海"
    }, {
        "i": "CNGDZJ",
        "t": "湛江"
    }, {
        "i": "CNGDZQ",
        "t": "肇庆"
    }, {
        "i": "CNGDZS",
        "t": "中山"
    }, {
        "i": "CNGSBY",
        "t": "白银市"
    }, {
        "i": "CNGSDX",
        "t": "定西"
    }, {
        "i": "CNGSGN",
        "t": "甘南藏族自治州"
    }, {
        "i": "CNGSJC",
        "t": "金昌市"
    }, {
        "i": "CNGSJQ",
        "t": "酒泉"
    }, {
        "i": "CNGSJY",
        "t": "嘉峪关"
    }, {
        "i": "CNGSLN",
        "t": "陇南"
    }, {
        "i": "CNGSLX",
        "t": "临夏回族自治州"
    }, {
        "i": "CNGSLZ",
        "t": "兰州"
    }, {
        "i": "CNGSPL",
        "t": "平凉"
    }, {
        "i": "CNGSQY",
        "t": "庆阳"
    }, {
        "i": "CNGSTS",
        "t": "天水"
    }, {
        "i": "CNGSWW",
        "t": "武威"
    }, {
        "i": "CNGSZY",
        "t": "张掖"
    }, {
        "i": "CNGXBH",
        "t": "北海"
    }, {
        "i": "CNGXBS",
        "t": "百色"
    }, {
        "i": "CNGXCZ",
        "t": "崇左"
    }, {
        "i": "CNGXFC",
        "t": "防城港"
    }, {
        "i": "CNGXGG",
        "t": "贵港"
    }, {
        "i": "CNGXGL",
        "t": "桂林"
    }, {
        "i": "CNGXHC",
        "t": "河池"
    }, {
        "i": "CNGXHZ",
        "t": "贺州"
    }, {
        "i": "CNGXLB",
        "t": "来宾"
    }, {
        "i": "CNGXLZ",
        "t": "柳州"
    }, {
        "i": "CNGXNN",
        "t": "南宁"
    }, {
        "i": "CNGXQZ",
        "t": "钦州"
    }, {
        "i": "CNGXWZ",
        "t": "梧州"
    }, {
        "i": "CNGXYL",
        "t": "玉林"
    }, {
        "i": "CNGZAS",
        "t": "安顺"
    }, {
        "i": "CNGZBJ",
        "t": "毕节"
    }, {
        "i": "CNGZGY",
        "t": "贵阳"
    }, {
        "i": "CNGZLP",
        "t": "六盘水"
    }, {
        "i": "CNGZQD",
        "t": "黔东南苗族侗族自治州"
    }, {
        "i": "CNGZQN",
        "t": "黔南布依族苗族自治州"
    }, {
        "i": "CNGZQX",
        "t": "黔西南布依族苗族自治州"
    }, {
        "i": "CNGZTR",
        "t": "铜仁"
    }, {
        "i": "CNGZZY",
        "t": "遵义"
    }, {
        "i": "CNHA90",
        "t": "省直辖县级行政区划"
    }, {
        "i": "CNHAAY",
        "t": "安阳"
    }, {
        "i": "CNHAHB",
        "t": "鹤壁"
    }, {
        "i": "CNHAJZ",
        "t": "焦作"
    }, {
        "i": "CNHAKF",
        "t": "开封"
    }, {
        "i": "CNHALH",
        "t": "漯河"
    }, {
        "i": "CNHALY",
        "t": "洛阳"
    }, {
        "i": "CNHANY",
        "t": "南阳"
    }, {
        "i": "CNHAPD",
        "t": "平顶山"
    }, {
        "i": "CNHAPY",
        "t": "濮阳"
    }, {
        "i": "CNHASM",
        "t": "三门峡"
    }, {
        "i": "CNHASQ",
        "t": "商丘"
    }, {
        "i": "CNHAXC",
        "t": "许昌"
    }, {
        "i": "CNHAXX",
        "t": "新乡"
    }, {
        "i": "CNHAXY",
        "t": "信阳"
    }, {
        "i": "CNHAZK",
        "t": "周口"
    }, {
        "i": "CNHAZM",
        "t": "驻马店"
    }, {
        "i": "CNHAZZ",
        "t": "郑州"
    }, {
        "i": "CNHB90",
        "t": "省直辖县级行政区划"
    }, {
        "i": "CNHBES",
        "t": "恩施"
    }, {
        "i": "CNHBEZ",
        "t": "鄂州"
    }, {
        "i": "CNHBHG",
        "t": "黄冈"
    }, {
        "i": "CNHBHS",
        "t": "黄石"
    }, {
        "i": "CNHBJM",
        "t": "荆门"
    }, {
        "i": "CNHBJZ",
        "t": "荆州"
    }, {
        "i": "CNHBSY",
        "t": "十堰"
    }, {
        "i": "CNHBSZ",
        "t": "随州"
    }, {
        "i": "CNHBWH",
        "t": "武汉"
    }, {
        "i": "CNHBXF",
        "t": "襄樊"
    }, {
        "i": "CNHBXG",
        "t": "孝感"
    }, {
        "i": "CNHBXN",
        "t": "咸宁"
    }, {
        "i": "CNHBYC",
        "t": "宜昌"
    }, {
        "i": "CNHEBD",
        "t": "保定"
    }, {
        "i": "CNHECD",
        "t": "承德"
    }, {
        "i": "CNHECZ",
        "t": "沧州"
    }, {
        "i": "CNHEHD",
        "t": "邯郸"
    }, {
        "i": "CNHEHS",
        "t": "衡水"
    }, {
        "i": "CNHELF",
        "t": "廊坊"
    }, {
        "i": "CNHEQH",
        "t": "秦皇岛"
    }, {
        "i": "CNHESJ",
        "t": "石家庄"
    }, {
        "i": "CNHETS",
        "t": "唐山"
    }, {
        "i": "CNHEXT",
        "t": "邢台"
    }, {
        "i": "CNHEZJ",
        "t": "张家口"
    }, {
        "i": "CNHI90",
        "t": "省直辖县级行政区划"
    }, {
        "i": "CNHIHK",
        "t": "海口"
    }, {
        "i": "CNHISY",
        "t": "三亚"
    }, {
        "i": "CNHLDQ",
        "t": "大庆"
    }, {
        "i": "CNHLDX",
        "t": "大兴安岭"
    }, {
        "i": "CNHLHE",
        "t": "哈尔滨"
    }, {
        "i": "CNHLHG",
        "t": "鹤岗"
    }, {
        "i": "CNHLHH",
        "t": "黑河"
    }, {
        "i": "CNHLJM",
        "t": "佳木斯"
    }, {
        "i": "CNHLJX",
        "t": "鸡西"
    }, {
        "i": "CNHLMD",
        "t": "牡丹江"
    }, {
        "i": "CNHLQQ",
        "t": "齐齐哈尔"
    }, {
        "i": "CNHLQT",
        "t": "七台河"
    }, {
        "i": "CNHLSH",
        "t": "绥化"
    }, {
        "i": "CNHLSY",
        "t": "双鸭山"
    }, {
        "i": "CNHLYC",
        "t": "伊春"
    }, {
        "i": "CNHNCD",
        "t": "常德"
    }, {
        "i": "CNHNCS",
        "t": "长沙"
    }, {
        "i": "CNHNCZ",
        "t": "郴州"
    }, {
        "i": "CNHNHH",
        "t": "怀化"
    }, {
        "i": "CNHNHY",
        "t": "衡阳"
    }, {
        "i": "CNHNIY",
        "t": "益阳"
    }, {
        "i": "CNHNLD",
        "t": "娄底"
    }, {
        "i": "CNHNSY",
        "t": "邵阳"
    }, {
        "i": "CNHNXT",
        "t": "湘潭"
    }, {
        "i": "CNHNXX",
        "t": "湘西土家族苗族自治州"
    }, {
        "i": "CNHNYY",
        "t": "岳阳"
    }, {
        "i": "CNHNYZ",
        "t": "永州"
    }, {
        "i": "CNHNZJ",
        "t": "张家界"
    }, {
        "i": "CNHNZZ",
        "t": "株洲"
    }, {
        "i": "CNJLBC",
        "t": "白城"
    }, {
        "i": "CNJLBS",
        "t": "白山"
    }, {
        "i": "CNJLCC",
        "t": "长春"
    }, {
        "i": "CNJLJL",
        "t": "吉林"
    }, {
        "i": "CNJLLY",
        "t": "辽源"
    }, {
        "i": "CNJLSP",
        "t": "四平"
    }, {
        "i": "CNJLSY",
        "t": "松原"
    }, {
        "i": "CNJLTH",
        "t": "通化"
    }, {
        "i": "CNJLYJ",
        "t": "延边"
    }, {
        "i": "CNJSCZ",
        "t": "常州"
    }, {
        "i": "CNJSHA",
        "t": "淮安"
    }, {
        "i": "CNJSLY",
        "t": "连云港"
    }, {
        "i": "CNJSNJ",
        "t": "南京"
    }, {
        "i": "CNJSNT",
        "t": "南通"
    }, {
        "i": "CNJSSQ",
        "t": "宿迁"
    }, {
        "i": "CNJSSZ",
        "t": "苏州"
    }, {
        "i": "CNJSTZ",
        "t": "泰州"
    }, {
        "i": "CNJSWX",
        "t": "无锡"
    }, {
        "i": "CNJSXZ",
        "t": "徐州"
    }, {
        "i": "CNJSYC",
        "t": "盐城"
    }, {
        "i": "CNJSYZ",
        "t": "扬州"
    }, {
        "i": "CNJSZJ",
        "t": "镇江"
    }, {
        "i": "CNJXFZ",
        "t": "抚州"
    }, {
        "i": "CNJXGZ",
        "t": "赣州"
    }, {
        "i": "CNJXJA",
        "t": "吉安"
    }, {
        "i": "CNJXJD",
        "t": "景德镇"
    }, {
        "i": "CNJXJJ",
        "t": "九江"
    }, {
        "i": "CNJXNC",
        "t": "南昌"
    }, {
        "i": "CNJXPX",
        "t": "萍乡"
    }, {
        "i": "CNJXSR",
        "t": "上饶"
    }, {
        "i": "CNJXXY",
        "t": "新余"
    }, {
        "i": "CNJXYC",
        "t": "宜春"
    }, {
        "i": "CNJXYT",
        "t": "鹰潭"
    }, {
        "i": "CNLNAS",
        "t": "鞍山"
    }, {
        "i": "CNLNBX",
        "t": "本溪"
    }, {
        "i": "CNLNCY",
        "t": "朝阳"
    }, {
        "i": "CNLNDD",
        "t": "丹东"
    }, {
        "i": "CNLNDL",
        "t": "大连"
    }, {
        "i": "CNLNFS",
        "t": "抚顺"
    }, {
        "i": "CNLNFX",
        "t": "阜新"
    }, {
        "i": "CNLNJX",
        "t": "葫芦岛"
    }, {
        "i": "CNLNJZ",
        "t": "锦州"
    }, {
        "i": "CNLNLY",
        "t": "辽阳"
    }, {
        "i": "CNLNPJ",
        "t": "盘锦"
    }, {
        "i": "CNLNSY",
        "t": "沈阳"
    }, {
        "i": "CNLNTL",
        "t": "铁岭"
    }, {
        "i": "CNLNYK",
        "t": "营口"
    }, {
        "i": "CNNMAL",
        "t": "阿拉善"
    }, {
        "i": "CNNMBT",
        "t": "包头"
    }, {
        "i": "CNNMBY",
        "t": "巴彦淖尔"
    }, {
        "i": "CNNMCF",
        "t": "赤峰"
    }, {
        "i": "CNNMEE",
        "t": "鄂尔多斯"
    }, {
        "i": "CNNMHH",
        "t": "呼和浩特"
    }, {
        "i": "CNNMHL",
        "t": "呼伦贝尔"
    }, {
        "i": "CNNMTL",
        "t": "通辽"
    }, {
        "i": "CNNMWH",
        "t": "乌海"
    }, {
        "i": "CNNMWM",
        "t": "乌兰察布"
    }, {
        "i": "CNNMXA",
        "t": "兴安盟"
    }, {
        "i": "CNNMXL",
        "t": "锡林郭勒"
    }, {
        "i": "CNNXGY",
        "t": "固原"
    }, {
        "i": "CNNXSZ",
        "t": "石嘴山"
    }, {
        "i": "CNNXWZ",
        "t": "吴忠"
    }, {
        "i": "CNNXYC",
        "t": "银川"
    }, {
        "i": "CNNXZW",
        "t": "中卫"
    }, {
        "i": "CNQHGL",
        "t": "果洛"
    }, {
        "i": "CNQHHB",
        "t": "海北"
    }, {
        "i": "CNQHHD",
        "t": "海东"
    }, {
        "i": "CNQHHH",
        "t": "黄南"
    }, {
        "i": "CNQHHN",
        "t": "海南"
    }, {
        "i": "CNQHHX",
        "t": "海西"
    }, {
        "i": "CNQHXN",
        "t": "西宁"
    }, {
        "i": "CNQHYS",
        "t": "玉树"
    }, {
        "i": "CNSCAB",
        "t": "阿坝"
    }, {
        "i": "CNSCBZ",
        "t": "巴中"
    }, {
        "i": "CNSCCD",
        "t": "成都"
    }, {
        "i": "CNSCDY",
        "t": "德阳"
    }, {
        "i": "CNSCDZ",
        "t": "达州"
    }, {
        "i": "CNSCGA",
        "t": "广安"
    }, {
        "i": "CNSCGY",
        "t": "广元"
    }, {
        "i": "CNSCGZ",
        "t": "甘孜藏族自治州"
    }, {
        "i": "CNSCLS",
        "t": "乐山"
    }, {
        "i": "CNSCLZ",
        "t": "泸州"
    }, {
        "i": "CNSCMS",
        "t": "眉山"
    }, {
        "i": "CNSCMY",
        "t": "绵阳"
    }, {
        "i": "CNSCNC",
        "t": "南充"
    }, {
        "i": "CNSCNJ",
        "t": "内江"
    }, {
        "i": "CNSCPZ",
        "t": "攀枝花"
    }, {
        "i": "CNSCSN",
        "t": "遂宁"
    }, {
        "i": "CNSCXC",
        "t": "凉山彝族自治州"
    }, {
        "i": "CNSCYA",
        "t": "雅安"
    }, {
        "i": "CNSCYB",
        "t": "宜宾"
    }, {
        "i": "CNSCZG",
        "t": "自贡"
    }, {
        "i": "CNSCZY",
        "t": "资阳"
    }, {
        "i": "CNSDBZ",
        "t": "滨州"
    }, {
        "i": "CNSDDY",
        "t": "东营"
    }, {
        "i": "CNSDDZ",
        "t": "德州"
    }, {
        "i": "CNSDHZ",
        "t": "菏泽"
    }, {
        "i": "CNSDJI",
        "t": "济宁"
    }, {
        "i": "CNSDJN",
        "t": "济南"
    }, {
        "i": "CNSDLC",
        "t": "聊城"
    }, {
        "i": "CNSDLW",
        "t": "莱芜"
    }, {
        "i": "CNSDLY",
        "t": "临沂"
    }, {
        "i": "CNSDQD",
        "t": "青岛"
    }, {
        "i": "CNSDRZ",
        "t": "日照"
    }, {
        "i": "CNSDTA",
        "t": "泰安"
    }, {
        "i": "CNSDWF",
        "t": "潍坊"
    }, {
        "i": "CNSDWH",
        "t": "威海"
    }, {
        "i": "CNSDYT",
        "t": "烟台"
    }, {
        "i": "CNSDZB",
        "t": "淄博"
    }, {
        "i": "CNSDZZ",
        "t": "枣庄"
    }, {
        "i": "CNSXCZ",
        "t": "长治"
    }, {
        "i": "CNSXDT",
        "t": "大同"
    }, {
        "i": "CNSXJC",
        "t": "晋城"
    }, {
        "i": "CNSXJZ",
        "t": "晋中"
    }, {
        "i": "CNSXLF",
        "t": "临汾"
    }, {
        "i": "CNSXLL",
        "t": "吕梁"
    }, {
        "i": "CNSXQZ",
        "t": "忻州"
    }, {
        "i": "CNSXSZ",
        "t": "朔州"
    }, {
        "i": "CNSXTY",
        "t": "太原"
    }, {
        "i": "CNSXYC",
        "t": "运城"
    }, {
        "i": "CNSXYQ",
        "t": "阳泉"
    }, {
        "i": "CNXAAK",
        "t": "安康"
    }, {
        "i": "CNXABJ",
        "t": "宝鸡"
    }, {
        "i": "CNXAHZ",
        "t": "汉中"
    }, {
        "i": "CNXASL",
        "t": "商洛"
    }, {
        "i": "CNXATC",
        "t": "铜川"
    }, {
        "i": "CNXAWN",
        "t": "渭南"
    }, {
        "i": "CNXAXA",
        "t": "西安"
    }, {
        "i": "CNXAXY",
        "t": "咸阳"
    }, {
        "i": "CNXAYA",
        "t": "延安"
    }, {
        "i": "CNXAYL",
        "t": "榆林"
    }, {
        "i": "CNXJ90",
        "t": "自治区直辖县级行政区划"
    }, {
        "i": "CNXJAL",
        "t": "阿勒泰"
    }, {
        "i": "CNXJBE",
        "t": "博尔塔拉蒙古自治州"
    }, {
        "i": "CNXJBY",
        "t": "巴音"
    }, {
        "i": "CNXJCJ",
        "t": "昌吉"
    }, {
        "i": "CNXJEK",
        "t": "阿克苏"
    }, {
        "i": "CNXJHM",
        "t": "哈密"
    }, {
        "i": "CNXJHT",
        "t": "和田"
    }, {
        "i": "CNXJKE",
        "t": "克孜勒苏柯尔克孜自治州"
    }, {
        "i": "CNXJKL",
        "t": "克拉玛依"
    }, {
        "i": "CNXJKS",
        "t": "喀什"
    }, {
        "i": "CNXJTC",
        "t": "塔城"
    }, {
        "i": "CNXJTL",
        "t": "吐鲁番"
    }, {
        "i": "CNXJWL",
        "t": "乌鲁木齐"
    }, {
        "i": "CNXJYL",
        "t": "伊犁哈萨克自治州"
    }, {
        "i": "CNXZAL",
        "t": "阿里"
    }, {
        "i": "CNXZCD",
        "t": "昌都"
    }, {
        "i": "CNXZLS",
        "t": "拉萨"
    }, {
        "i": "CNXZLZ",
        "t": "林芝"
    }, {
        "i": "CNXZNQ",
        "t": "那曲"
    }, {
        "i": "CNXZRG",
        "t": "日喀则"
    }, {
        "i": "CNXZSN",
        "t": "山南"
    }, {
        "i": "CNYNBS",
        "t": "保山"
    }, {
        "i": "CNYNCX",
        "t": "楚雄"
    }, {
        "i": "CNYNDH",
        "t": "德宏傣族景颇族自治州"
    }, {
        "i": "CNYNDL",
        "t": "大理"
    }, {
        "i": "CNYNDQ",
        "t": "迪庆"
    }, {
        "i": "CNYNHH",
        "t": "红河哈尼族彝族自治州"
    }, {
        "i": "CNYNKM",
        "t": "昆明"
    }, {
        "i": "CNYNLC",
        "t": "临沧"
    }, {
        "i": "CNYNLJ",
        "t": "丽江"
    }, {
        "i": "CNYNNJ",
        "t": "怒江"
    }, {
        "i": "CNYNQJ",
        "t": "曲靖"
    }, {
        "i": "CNYNSM",
        "t": "普洱市"
    }, {
        "i": "CNYNWS",
        "t": "文山"
    }, {
        "i": "CNYNXS",
        "t": "西双版纳"
    }, {
        "i": "CNYNYX",
        "t": "玉溪"
    }, {
        "i": "CNYNZT",
        "t": "昭通"
    }, {
        "i": "CNZJHU",
        "t": "湖州"
    }, {
        "i": "CNZJHZ",
        "t": "杭州"
    }, {
        "i": "CNZJJH",
        "t": "金华"
    }, {
        "i": "CNZJJX",
        "t": "嘉兴"
    }, {
        "i": "CNZJLS",
        "t": "丽水"
    }, {
        "i": "CNZJNB",
        "t": "宁波"
    }, {
        "i": "CNZJQZ",
        "t": "衢州"
    }, {
        "i": "CNZJSX",
        "t": "绍兴"
    }, {
        "i": "CNZJTZ",
        "t": "台州"
    }, {
        "i": "CNZJWZ",
        "t": "温州"
    }, {
        "i": "CNZJZS",
        "t": "舟山"
    }],
    "shortcuts": [{
        "title": "一线城市",
        "ids": ["CNBJ00", "CNTJ00", "CNSH00", "CNGDSZ"]
    }, {
        "title": "东北",
        "ids": ["CNLNAS", "CNLNBX", "CNLNCY", "CNLNDD", "CNLNDL", "CNLNFS", "CNLNFX", "CNLNJX", "CNLNJZ", "CNLNLY", "CNLNPJ", "CNLNSY", "CNLNTL", "CNLNYK", "CNJLBC", "CNJLBS", "CNJLCC", "CNJLJL", "CNJLLY", "CNJLSP", "CNJLSY", "CNJLTH", "CNJLYJ", "CNHLDQ", "CNHLDX", "CNHLHE", "CNHLHG", "CNHLHH", "CNHLJM", "CNHLJX", "CNHLMD", "CNHLQQ", "CNHLQT", "CNHLSH", "CNHLSY", "CNHLYC"]
    }, {
        "title": "华北",
        "ids": ["CNSDBZ", "CNSDDY", "CNSDDZ", "CNSDHZ", "CNSDJI", "CNSDJN", "CNSDLC", "CNSDLW", "CNSDLY", "CNSDQD", "CNSDRZ", "CNSDTA", "CNSDWF", "CNSDWH", "CNSDYT", "CNSDZB", "CNSDZZ", "CNTJ00", "CNSXCZ", "CNSXDT", "CNSXJC", "CNSXJZ", "CNSXLF", "CNSXLL", "CNSXQZ", "CNSXSZ", "CNSXTY", "CNSXYC", "CNSXYQ", "CNHEBD", "CNHECD", "CNHECZ", "CNHEHD", "CNHEHS", "CNHELF", "CNHEQH", "CNHESJ", "CNHETS", "CNHEXT", "CNHEZJ", "CNHA90", "CNHAAY", "CNHAHB", "CNHAJZ", "CNHAKF", "CNHALH", "CNHALY", "CNHANY", "CNHAPD", "CNHAPY", "CNHASM", "CNHASQ", "CNHAXC", "CNHAXX", "CNHAXY", "CNHAZK", "CNHAZM", "CNHAZZ", "CNXAAK", "CNXABJ", "CNXAHZ", "CNXASL", "CNXATC", "CNXAWN", "CNXAXA", "CNXAXY", "CNXAYA", "CNXAYL", "CNBJ00"]
    }, {
        "title": "华东",
        "ids": ["CNJSCZ", "CNJSHA", "CNJSLY", "CNJSNJ", "CNJSNT", "CNJSSQ", "CNJSSZ", "CNJSTZ", "CNJSWX", "CNJSXZ", "CNJSYC", "CNJSYZ", "CNJSZJ", "CNZJHU", "CNZJHZ", "CNZJJH", "CNZJJX", "CNZJLS", "CNZJNB", "CNZJQZ", "CNZJSX", "CNZJTZ", "CNZJWZ", "CNZJZS", "CNAHAQ", "CNAHBB", "CNAHCH", "CNAHCO", "CNAHCZ", "CNAHFY", "CNAHHB", "CNAHHF", "CNAHHN", "CNAHHS", "CNAHHZ", "CNAHLA", "CNAHMA", "CNAHSZ", "CNAHTL", "CNAHWH", "CNAHXC", "CNJXFZ", "CNJXGZ", "CNJXJA", "CNJXJD", "CNJXJJ", "CNJXNC", "CNJXPX", "CNJXSR", "CNJXXY", "CNJXYC", "CNJXYT", "CNSH00"]
    }, {
        "title": "华中",
        "ids": ["CNCQ00", "CNHB90", "CNHBES", "CNHBEZ", "CNHBHG", "CNHBHS", "CNHBJM", "CNHBJZ", "CNHBSY", "CNHBSZ", "CNHBWH", "CNHBXF", "CNHBXG", "CNHBXN", "CNHBYC", "CNHNCD", "CNHNCS", "CNHNCZ", "CNHNHH", "CNHNHY", "CNHNIY", "CNHNLD", "CNHNSY", "CNHNXT", "CNHNXX", "CNHNYY", "CNHNYZ", "CNHNZJ", "CNHNZZ", "CNSCAB", "CNSCBZ", "CNSCCD", "CNSCDY", "CNSCDZ", "CNSCGA", "CNSCGY", "CNSCGZ", "CNSCLS", "CNSCLZ", "CNSCMS", "CNSCMY", "CNSCNC", "CNSCNJ", "CNSCPZ", "CNSCSN", "CNSCXC", "CNSCYA", "CNSCYB", "CNSCZG", "CNSCZY"]
    }, {
        "title": "华南",
        "ids": ["CNGDCZ", "CNGDDG", "CNGDFS", "CNGDGZ", "CNGDHY", "CNGDHZ", "CNGDJM", "CNGDJY", "CNGDMM", "CNGDMZ", "CNGDQY", "CNGDSG", "CNGDST", "CNGDSW", "CNGDSZ", "CNGDYF", "CNGDYJ", "CNGDZH", "CNGDZJ", "CNGDZQ", "CNGDZS", "CNGXBH", "CNGXBS", "CNGXCZ", "CNGXFC", "CNGXGG", "CNGXGL", "CNGXHC", "CNGXHZ", "CNGXLB", "CNGXLZ", "CNGXNN", "CNGXQZ", "CNGXWZ", "CNGXYL", "CNHI90", "CNHIHK", "CNHISY", "CNFJFZ", "CNFJLY", "CNFJND", "CNFJNP", "CNFJPT", "CNFJQZ", "CNFJSM", "CNFJXM", "CNFJZZ", "CNYNBS", "CNYNCX", "CNYNDH", "CNYNDL", "CNYNDQ", "CNYNHH", "CNYNKM", "CNYNLC", "CNYNLJ", "CNYNNJ", "CNYNQJ", "CNYNSM", "CNYNWS", "CNYNXS", "CNYNYX", "CNYNZT", "CNGZAS", "CNGZBJ", "CNGZGY", "CNGZLP", "CNGZQD", "CNGZQN", "CNGZQX", "CNGZTR", "CNGZZY", "CNTW00", "CNHK00", "CNMO00"]
    }, {
        "title": "西部",
        "ids": ["CNGSBY", "CNGSDX", "CNGSGN", "CNGSJC", "CNGSJQ", "CNGSJY", "CNGSLN", "CNGSLX", "CNGSLZ", "CNGSPL", "CNGSQY", "CNGSTS", "CNGSWW", "CNGSZY", "CNNXGY", "CNNXSZ", "CNNXWZ", "CNNXYC", "CNNXZW", "CNQHGL", "CNQHHB", "CNQHHD", "CNQHHH", "CNQHHN", "CNQHHX", "CNQHXN", "CNQHYS", "CNXZAL", "CNXZCD", "CNXZLS", "CNXZLZ", "CNXZNQ", "CNXZRG", "CNXZSN", "CNXJ90", "CNXJAL", "CNXJBE", "CNXJBY", "CNXJCJ", "CNXJEK", "CNXJHM", "CNXJHT", "CNXJKE", "CNXJKL", "CNXJKS", "CNXJTC", "CNXJTL", "CNXJWL", "CNXJYL", "CNNMAL", "CNNMBT", "CNNMBY", "CNNMCF", "CNNMEE", "CNNMHH", "CNNMHL", "CNNMTL", "CNNMWH", "CNNMWM", "CNNMXA", "CNNMXL"]
    }],
    "selectedItems": []
};
