var data={
    "result": 1,
    "msg": "",
    "data": {
        "adsInfo": {
            "adspaceId": "1430",
            "siteName": "影音播放",
            "channelName": "医疗健康大类",
            "adspaceName": "tracy_adspace-copy",
            "type": "通栏广告",
            "size": "970*90",
            "position": "第一屏",
            "adfomat": ["jpg ", "gif ", "swf "],
            "price": "0.01",
            "seller": "Allyes_TestSeller"
        },
        "selected": "",
        "helper": [{
            "code": "CNBJ",
            "name": "北京",
            "level": "1"
        }, {
            "code": "CNTJ",
            "name": "天津",
            "level": "1"
        }, {
            "code": "CNHE",
            "name": "河北",
            "children": [{
                "code": "CNHESJ",
                "name": "石家庄",
                "level": "2"
            }, {
                "code": "CNHETS",
                "name": "唐山",
                "level": "2"
            }, {
                "code": "CNHEQH",
                "name": "秦皇岛",
                "level": "0"
            }, {
                "code": "CNHEHD",
                "name": "邯郸",
                "level": "0"
            }, {
                "code": "CNHEXT",
                "name": "邢台",
                "level": "0"
            }, {
                "code": "CNHEBD",
                "name": "保定",
                "level": "0"
            }, {
                "code": "CNHEZJ",
                "name": "张家口",
                "level": "0"
            }, {
                "code": "CNHECD",
                "name": "承德",
                "level": "0"
            }, {
                "code": "CNHECZ",
                "name": "沧州",
                "level": "0"
            }, {
                "code": "CNHELF",
                "name": "廊坊",
                "level": "0"
            }, {
                "code": "CNHEHS",
                "name": "衡水",
                "level": "0"
            }]
        }, {
            "code": "CNSX",
            "name": "山西",
            "children": [{
                "code": "CNSXTY",
                "name": "太原",
                "level": "2"
            }, {
                "code": "CNSXDT",
                "name": "大同",
                "level": "0"
            }, {
                "code": "CNSXYQ",
                "name": "阳泉",
                "level": "0"
            }, {
                "code": "CNSXCZ",
                "name": "长治",
                "level": "0"
            }, {
                "code": "CNSXJC",
                "name": "晋城",
                "level": "0"
            }, {
                "code": "CNSXSZ",
                "name": "朔州",
                "level": "0"
            }, {
                "code": "CNSXJZ",
                "name": "晋中",
                "level": "0"
            }, {
                "code": "CNSXYC",
                "name": "运城",
                "level": "0"
            }, {
                "code": "CNSXQZ",
                "name": "忻州",
                "level": "0"
            }, {
                "code": "CNSXLF",
                "name": "临汾",
                "level": "0"
            }, {
                "code": "CNSXLL",
                "name": "吕梁",
                "level": "0"
            }]
        }, {
            "code": "CNNM",
            "name": "内蒙古",
            "children": [{
                "code": "CNNMHH",
                "name": "呼和浩特",
                "level": "0"
            }, {
                "code": "CNNMBT",
                "name": "包头",
                "level": "0"
            }, {
                "code": "CNNMWH",
                "name": "乌海",
                "level": "0"
            }, {
                "code": "CNNMCF",
                "name": "赤峰",
                "level": "0"
            }, {
                "code": "CNNMTL",
                "name": "通辽",
                "level": "0"
            }, {
                "code": "CNNMEE",
                "name": "鄂尔多斯",
                "level": "0"
            }, {
                "code": "CNNMHL",
                "name": "呼伦贝尔",
                "level": "0"
            }, {
                "code": "CNNMBY",
                "name": "巴彦淖尔",
                "level": "0"
            }, {
                "code": "CNNMWM",
                "name": "乌兰察布",
                "level": "0"
            }, {
                "code": "CNNMXA",
                "name": "兴安盟",
                "level": "0"
            }, {
                "code": "CNNMXL",
                "name": "锡林郭勒",
                "level": "0"
            }, {
                "code": "CNNMAL",
                "name": "阿拉善",
                "level": "0"
            }]
        }, {
            "code": "CNLN",
            "name": "辽宁",
            "children": [{
                "code": "CNLNSY",
                "name": "沈阳",
                "level": "2"
            }, {
                "code": "CNLNDL",
                "name": "大连",
                "level": "2"
            }, {
                "code": "CNLNAS",
                "name": "鞍山",
                "level": "0"
            }, {
                "code": "CNLNFS",
                "name": "抚顺",
                "level": "0"
            }, {
                "code": "CNLNBX",
                "name": "本溪",
                "level": "0"
            }, {
                "code": "CNLNDD",
                "name": "丹东",
                "level": "0"
            }, {
                "code": "CNLNJZ",
                "name": "锦州",
                "level": "0"
            }, {
                "code": "CNLNYK",
                "name": "营口",
                "level": "0"
            }, {
                "code": "CNLNFX",
                "name": "阜新",
                "level": "0"
            }, {
                "code": "CNLNLY",
                "name": "辽阳",
                "level": "0"
            }, {
                "code": "CNLNPJ",
                "name": "盘锦",
                "level": "0"
            }, {
                "code": "CNLNTL",
                "name": "铁岭",
                "level": "0"
            }, {
                "code": "CNLNCY",
                "name": "朝阳",
                "level": "0"
            }, {
                "code": "CNLNJX",
                "name": "葫芦岛",
                "level": "0"
            }]
        }, {
            "code": "CNJL",
            "name": "吉林",
            "children": [{
                "code": "CNJLCC",
                "name": "长春",
                "level": "2"
            }, {
                "code": "CNJLJL",
                "name": "吉林",
                "level": "0"
            }, {
                "code": "CNJLSP",
                "name": "四平",
                "level": "0"
            }, {
                "code": "CNJLLY",
                "name": "辽源",
                "level": "0"
            }, {
                "code": "CNJLTH",
                "name": "通化",
                "level": "0"
            }, {
                "code": "CNJLBS",
                "name": "白山",
                "level": "0"
            }, {
                "code": "CNJLSY",
                "name": "松原",
                "level": "0"
            }, {
                "code": "CNJLBC",
                "name": "白城",
                "level": "0"
            }, {
                "code": "CNJLYJ",
                "name": "延边",
                "level": "0"
            }]
        }, {
            "code": "CNHL",
            "name": "黑龙江",
            "children": [{
                "code": "CNHLHE",
                "name": "哈尔滨",
                "level": "2"
            }, {
                "code": "CNHLQQ",
                "name": "齐齐哈尔",
                "level": "0"
            }, {
                "code": "CNHLJX",
                "name": "鸡西",
                "level": "0"
            }, {
                "code": "CNHLHG",
                "name": "鹤岗",
                "level": "0"
            }, {
                "code": "CNHLSY",
                "name": "双鸭山",
                "level": "0"
            }, {
                "code": "CNHLDQ",
                "name": "大庆",
                "level": "0"
            }, {
                "code": "CNHLYC",
                "name": "伊春",
                "level": "0"
            }, {
                "code": "CNHLJM",
                "name": "佳木斯",
                "level": "0"
            }, {
                "code": "CNHLQT",
                "name": "七台河",
                "level": "0"
            }, {
                "code": "CNHLMD",
                "name": "牡丹江",
                "level": "0"
            }, {
                "code": "CNHLHH",
                "name": "黑河",
                "level": "0"
            }, {
                "code": "CNHLSH",
                "name": "绥化",
                "level": "0"
            }, {
                "code": "CNHLDX",
                "name": "大兴安岭",
                "level": "0"
            }]
        }, {
            "code": "CNSH",
            "name": "上海",
            "level": "1"
        }, {
            "code": "CNJS",
            "name": "江苏",
            "children": [{
                "code": "CNJSNJ",
                "name": "南京",
                "level": "2"
            }, {
                "code": "CNJSWX",
                "name": "无锡",
                "level": "2"
            }, {
                "code": "CNJSXZ",
                "name": "徐州",
                "level": "0"
            }, {
                "code": "CNJSCZ",
                "name": "常州",
                "level": "0"
            }, {
                "code": "CNJSSZ",
                "name": "苏州",
                "level": "2"
            }, {
                "code": "CNJSNT",
                "name": "南通",
                "level": "0"
            }, {
                "code": "CNJSLY",
                "name": "连云港",
                "level": "0"
            }, {
                "code": "CNJSHA",
                "name": "淮安",
                "level": "0"
            }, {
                "code": "CNJSYC",
                "name": "盐城",
                "level": "0"
            }, {
                "code": "CNJSYZ",
                "name": "扬州",
                "level": "0"
            }, {
                "code": "CNJSZJ",
                "name": "镇江",
                "level": "0"
            }, {
                "code": "CNJSTZ",
                "name": "泰州",
                "level": "0"
            }, {
                "code": "CNJSSQ",
                "name": "宿迁",
                "level": "0"
            }]
        }, {
            "code": "CNZJ",
            "name": "浙江",
            "children": [{
                "code": "CNZJHZ",
                "name": "杭州",
                "level": "2"
            }, {
                "code": "CNZJNB",
                "name": "宁波",
                "level": "2"
            }, {
                "code": "CNZJWZ",
                "name": "温州",
                "level": "2"
            }, {
                "code": "CNZJJX",
                "name": "嘉兴",
                "level": "0"
            }, {
                "code": "CNZJHU",
                "name": "湖州",
                "level": "0"
            }, {
                "code": "CNZJSX",
                "name": "绍兴",
                "level": "0"
            }, {
                "code": "CNZJJH",
                "name": "金华",
                "level": "0"
            }, {
                "code": "CNZJQZ",
                "name": "衢州",
                "level": "0"
            }, {
                "code": "CNZJZS",
                "name": "舟山",
                "level": "0"
            }, {
                "code": "CNZJTZ",
                "name": "台州",
                "level": "0"
            }, {
                "code": "CNZJLS",
                "name": "丽水",
                "level": "0"
            }]
        }, {
            "code": "CNAH",
            "name": "安徽",
            "children": [{
                "code": "CNAHHF",
                "name": "合肥",
                "level": "2"
            }, {
                "code": "CNAHWH",
                "name": "芜湖",
                "level": "0"
            }, {
                "code": "CNAHBB",
                "name": "蚌埠",
                "level": "0"
            }, {
                "code": "CNAHHN",
                "name": "淮南",
                "level": "0"
            }, {
                "code": "CNAHMA",
                "name": "马鞍山",
                "level": "0"
            }, {
                "code": "CNAHHB",
                "name": "淮北",
                "level": "0"
            }, {
                "code": "CNAHTL",
                "name": "铜陵",
                "level": "0"
            }, {
                "code": "CNAHAQ",
                "name": "安庆",
                "level": "0"
            }, {
                "code": "CNAHHS",
                "name": "黄山",
                "level": "0"
            }, {
                "code": "CNAHCZ",
                "name": "滁州",
                "level": "0"
            }, {
                "code": "CNAHFY",
                "name": "阜阳",
                "level": "0"
            }, {
                "code": "CNAHSZ",
                "name": "宿州",
                "level": "0"
            }, {
                "code": "CNAHCH",
                "name": "巢湖",
                "level": "0"
            }, {
                "code": "CNAHLA",
                "name": "六安",
                "level": "0"
            }, {
                "code": "CNAHHZ",
                "name": "亳州",
                "level": "0"
            }, {
                "code": "CNAHCO",
                "name": "池州",
                "level": "0"
            }, {
                "code": "CNAHXC",
                "name": "宣城",
                "level": "0"
            }]
        }, {
            "code": "CNFJ",
            "name": "福建",
            "children": [{
                "code": "CNFJFZ",
                "name": "福州",
                "level": "2"
            }, {
                "code": "CNFJXM",
                "name": "厦门",
                "level": "2"
            }, {
                "code": "CNFJPT",
                "name": "莆田",
                "level": "0"
            }, {
                "code": "CNFJSM",
                "name": "三明",
                "level": "0"
            }, {
                "code": "CNFJQZ",
                "name": "泉州",
                "level": "0"
            }, {
                "code": "CNFJZZ",
                "name": "漳州",
                "level": "0"
            }, {
                "code": "CNFJNP",
                "name": "南平",
                "level": "0"
            }, {
                "code": "CNFJLY",
                "name": "龙岩",
                "level": "0"
            }, {
                "code": "CNFJND",
                "name": "宁德",
                "level": "0"
            }]
        }, {
            "code": "CNJX",
            "name": "江西",
            "children": [{
                "code": "CNJXNC",
                "name": "南昌",
                "level": "2"
            }, {
                "code": "CNJXJD",
                "name": "景德镇",
                "level": "0"
            }, {
                "code": "CNJXPX",
                "name": "萍乡",
                "level": "0"
            }, {
                "code": "CNJXJJ",
                "name": "九江",
                "level": "0"
            }, {
                "code": "CNJXXY",
                "name": "新余",
                "level": "0"
            }, {
                "code": "CNJXYT",
                "name": "鹰潭",
                "level": "0"
            }, {
                "code": "CNJXGZ",
                "name": "赣州",
                "level": "0"
            }, {
                "code": "CNJXJA",
                "name": "吉安",
                "level": "0"
            }, {
                "code": "CNJXYC",
                "name": "宜春",
                "level": "0"
            }, {
                "code": "CNJXFZ",
                "name": "抚州",
                "level": "0"
            }, {
                "code": "CNJXSR",
                "name": "上饶",
                "level": "0"
            }]
        }, {
            "code": "CNSD",
            "name": "山东",
            "children": [{
                "code": "CNSDJN",
                "name": "济南",
                "level": "2"
            }, {
                "code": "CNSDQD",
                "name": "青岛",
                "level": "2"
            }, {
                "code": "CNSDZB",
                "name": "淄博",
                "level": "2"
            }, {
                "code": "CNSDZZ",
                "name": "枣庄",
                "level": "0"
            }, {
                "code": "CNSDDY",
                "name": "东营",
                "level": "0"
            }, {
                "code": "CNSDYT",
                "name": "烟台",
                "level": "2"
            }, {
                "code": "CNSDWF",
                "name": "潍坊",
                "level": "0"
            }, {
                "code": "CNSDJI",
                "name": "济宁",
                "level": "0"
            }, {
                "code": "CNSDTA",
                "name": "泰安",
                "level": "0"
            }, {
                "code": "CNSDWH",
                "name": "威海",
                "level": "0"
            }, {
                "code": "CNSDRZ",
                "name": "日照",
                "level": "0"
            }, {
                "code": "CNSDLW",
                "name": "莱芜",
                "level": "0"
            }, {
                "code": "CNSDLY",
                "name": "临沂",
                "level": "0"
            }, {
                "code": "CNSDDZ",
                "name": "德州",
                "level": "0"
            }, {
                "code": "CNSDLC",
                "name": "聊城",
                "level": "0"
            }, {
                "code": "CNSDBZ",
                "name": "滨州",
                "level": "0"
            }, {
                "code": "CNSDHZ",
                "name": "菏泽",
                "level": "0"
            }]
        }, {
            "code": "CNHA",
            "name": "河南",
            "children": [{
                "code": "CNHAZZ",
                "name": "郑州",
                "level": "2"
            }, {
                "code": "CNHAKF",
                "name": "开封",
                "level": "0"
            }, {
                "code": "CNHALY",
                "name": "洛阳",
                "level": "0"
            }, {
                "code": "CNHAPD",
                "name": "平顶山",
                "level": "0"
            }, {
                "code": "CNHAAY",
                "name": "安阳",
                "level": "0"
            }, {
                "code": "CNHAHB",
                "name": "鹤壁",
                "level": "0"
            }, {
                "code": "CNHAXX",
                "name": "新乡",
                "level": "0"
            }, {
                "code": "CNHAJZ",
                "name": "焦作",
                "level": "0"
            }, {
                "code": "CNHAPY",
                "name": "濮阳",
                "level": "0"
            }, {
                "code": "CNHAXC",
                "name": "许昌",
                "level": "0"
            }, {
                "code": "CNHALH",
                "name": "漯河",
                "level": "0"
            }, {
                "code": "CNHASM",
                "name": "三门峡",
                "level": "0"
            }, {
                "code": "CNHANY",
                "name": "南阳",
                "level": "0"
            }, {
                "code": "CNHASQ",
                "name": "商丘",
                "level": "0"
            }, {
                "code": "CNHAXY",
                "name": "信阳",
                "level": "0"
            }, {
                "code": "CNHAZK",
                "name": "周口",
                "level": "0"
            }, {
                "code": "CNHAZM",
                "name": "驻马店",
                "level": "0"
            }]
        }, {
            "code": "CNHB",
            "name": "湖北",
            "children": [{
                "code": "CNHBWH",
                "name": "武汉",
                "level": "2"
            }, {
                "code": "CNHBHS",
                "name": "黄石",
                "level": "0"
            }, {
                "code": "CNHBSY",
                "name": "十堰",
                "level": "0"
            }, {
                "code": "CNHBYC",
                "name": "宜昌",
                "level": "0"
            }, {
                "code": "CNHBXF",
                "name": "襄樊",
                "level": "0"
            }, {
                "code": "CNHBEZ",
                "name": "鄂州",
                "level": "0"
            }, {
                "code": "CNHBJM",
                "name": "荆门",
                "level": "0"
            }, {
                "code": "CNHBXG",
                "name": "孝感",
                "level": "0"
            }, {
                "code": "CNHBJZ",
                "name": "荆州",
                "level": "0"
            }, {
                "code": "CNHBHG",
                "name": "黄冈",
                "level": "0"
            }, {
                "code": "CNHBXN",
                "name": "咸宁",
                "level": "0"
            }, {
                "code": "CNHBSZ",
                "name": "随州",
                "level": "0"
            }, {
                "code": "CNHBES",
                "name": "恩施",
                "level": "0"
            }]
        }, {
            "code": "CNHN",
            "name": "湖南",
            "children": [{
                "code": "CNHNCS",
                "name": "长沙",
                "level": "2"
            }, {
                "code": "CNHNZZ",
                "name": "株洲",
                "level": "0"
            }, {
                "code": "CNHNXT",
                "name": "湘潭",
                "level": "0"
            }, {
                "code": "CNHNHY",
                "name": "衡阳",
                "level": "0"
            }, {
                "code": "CNHNSY",
                "name": "邵阳",
                "level": "0"
            }, {
                "code": "CNHNYY",
                "name": "岳阳",
                "level": "0"
            }, {
                "code": "CNHNCD",
                "name": "常德",
                "level": "0"
            }, {
                "code": "CNHNZJ",
                "name": "张家界",
                "level": "0"
            }, {
                "code": "CNHNIY",
                "name": "益阳",
                "level": "0"
            }, {
                "code": "CNHNCZ",
                "name": "郴州",
                "level": "0"
            }, {
                "code": "CNHNYZ",
                "name": "永州",
                "level": "0"
            }, {
                "code": "CNHNHH",
                "name": "怀化",
                "level": "0"
            }, {
                "code": "CNHNLD",
                "name": "娄底",
                "level": "0"
            }, {
                "code": "CNHNXX",
                "name": "湘西土家族苗族自治州",
                "level": "0"
            }]
        }, {
            "code": "CNGD",
            "name": "广东",
            "children": [{
                "code": "CNGDGZ",
                "name": "广州",
                "level": "1"
            }, {
                "code": "CNGDSG",
                "name": "韶关",
                "level": "0"
            }, {
                "code": "CNGDSZ",
                "name": "深圳",
                "level": "1"
            }, {
                "code": "CNGDZH",
                "name": "珠海",
                "level": "0"
            }, {
                "code": "CNGDST",
                "name": "汕头",
                "level": "0"
            }, {
                "code": "CNGDFS",
                "name": "佛山",
                "level": "2"
            }, {
                "code": "CNGDJM",
                "name": "江门",
                "level": "0"
            }, {
                "code": "CNGDZJ",
                "name": "湛江",
                "level": "0"
            }, {
                "code": "CNGDMM",
                "name": "茂名",
                "level": "0"
            }, {
                "code": "CNGDZQ",
                "name": "肇庆",
                "level": "0"
            }, {
                "code": "CNGDHZ",
                "name": "惠州",
                "level": "0"
            }, {
                "code": "CNGDMZ",
                "name": "梅州",
                "level": "0"
            }, {
                "code": "CNGDSW",
                "name": "汕尾",
                "level": "0"
            }, {
                "code": "CNGDHY",
                "name": "河源",
                "level": "0"
            }, {
                "code": "CNGDYJ",
                "name": "阳江",
                "level": "0"
            }, {
                "code": "CNGDQY",
                "name": "清远",
                "level": "0"
            }, {
                "code": "CNGDDG",
                "name": "东莞",
                "level": "2"
            }, {
                "code": "CNGDZS",
                "name": "中山",
                "level": "0"
            }, {
                "code": "CNGDCZ",
                "name": "潮州",
                "level": "0"
            }, {
                "code": "CNGDJY",
                "name": "揭阳",
                "level": "0"
            }, {
                "code": "CNGDYF",
                "name": "云浮",
                "level": "0"
            }]
        }, {
            "code": "CNGX",
            "name": "广西",
            "children": [{
                "code": "CNGXNN",
                "name": "南宁",
                "level": "2"
            }, {
                "code": "CNGXLZ",
                "name": "柳州",
                "level": "0"
            }, {
                "code": "CNGXGL",
                "name": "桂林",
                "level": "0"
            }, {
                "code": "CNGXWZ",
                "name": "梧州",
                "level": "0"
            }, {
                "code": "CNGXBH",
                "name": "北海",
                "level": "0"
            }, {
                "code": "CNGXFC",
                "name": "防城港",
                "level": "0"
            }, {
                "code": "CNGXQZ",
                "name": "钦州",
                "level": "0"
            }, {
                "code": "CNGXGG",
                "name": "贵港",
                "level": "0"
            }, {
                "code": "CNGXYL",
                "name": "玉林",
                "level": "0"
            }, {
                "code": "CNGXBS",
                "name": "百色",
                "level": "0"
            }, {
                "code": "CNGXHZ",
                "name": "贺州",
                "level": "0"
            }, {
                "code": "CNGXHC",
                "name": "河池",
                "level": "0"
            }, {
                "code": "CNGXLB",
                "name": "来宾",
                "level": "0"
            }, {
                "code": "CNGXCZ",
                "name": "崇左",
                "level": "0"
            }]
        }, {
            "code": "CNHI",
            "name": "海南",
            "children": [{
                "code": "CNHIHK",
                "name": "海口",
                "level": "0"
            }, {
                "code": "CNHISY",
                "name": "三亚",
                "level": "0"
            }]
        }, {
            "code": "CNCQ",
            "name": "重庆",
            "level": "1"
        }, {
            "code": "CNSC",
            "name": "四川",
            "children": [{
                "code": "CNSCCD",
                "name": "成都",
                "level": "2"
            }, {
                "code": "CNSCZG",
                "name": "自贡",
                "level": "0"
            }, {
                "code": "CNSCPZ",
                "name": "攀枝花",
                "level": "0"
            }, {
                "code": "CNSCLZ",
                "name": "泸州",
                "level": "0"
            }, {
                "code": "CNSCDY",
                "name": "德阳",
                "level": "0"
            }, {
                "code": "CNSCMY",
                "name": "绵阳",
                "level": "0"
            }, {
                "code": "CNSCGY",
                "name": "广元",
                "level": "0"
            }, {
                "code": "CNSCSN",
                "name": "遂宁",
                "level": "0"
            }, {
                "code": "CNSCNJ",
                "name": "内江",
                "level": "0"
            }, {
                "code": "CNSCLS",
                "name": "乐山",
                "level": "0"
            }, {
                "code": "CNSCNC",
                "name": "南充",
                "level": "0"
            }, {
                "code": "CNSCMS",
                "name": "眉山",
                "level": "0"
            }, {
                "code": "CNSCYB",
                "name": "宜宾",
                "level": "0"
            }, {
                "code": "CNSCGA",
                "name": "广安",
                "level": "0"
            }, {
                "code": "CNSCDZ",
                "name": "达州",
                "level": "0"
            }, {
                "code": "CNSCYA",
                "name": "雅安",
                "level": "0"
            }, {
                "code": "CNSCBZ",
                "name": "巴中",
                "level": "0"
            }, {
                "code": "CNSCZY",
                "name": "资阳",
                "level": "0"
            }, {
                "code": "CNSCAB",
                "name": "阿坝",
                "level": "0"
            }, {
                "code": "CNSCGZ",
                "name": "甘孜藏族自治州",
                "level": "0"
            }, {
                "code": "CNSCXC",
                "name": "凉山彝族自治州",
                "level": "0"
            }]
        }, {
            "code": "CNGZ",
            "name": "贵州",
            "children": [{
                "code": "CNGZGY",
                "name": "贵阳",
                "level": "0"
            }, {
                "code": "CNGZLP",
                "name": "六盘水",
                "level": "0"
            }, {
                "code": "CNGZZY",
                "name": "遵义",
                "level": "0"
            }, {
                "code": "CNGZAS",
                "name": "安顺",
                "level": "0"
            }, {
                "code": "CNGZTR",
                "name": "铜仁",
                "level": "0"
            }, {
                "code": "CNGZQX",
                "name": "黔西南布依族苗族自治州",
                "level": "0"
            }, {
                "code": "CNGZBJ",
                "name": "毕节",
                "level": "0"
            }, {
                "code": "CNGZQD",
                "name": "黔东南苗族侗族自治州",
                "level": "0"
            }, {
                "code": "CNGZQN",
                "name": "黔南布依族苗族自治州",
                "level": "0"
            }]
        }, {
            "code": "CNYN",
            "name": "云南",
            "children": [{
                "code": "CNYNKM",
                "name": "昆明",
                "level": "2"
            }, {
                "code": "CNYNQJ",
                "name": "曲靖",
                "level": "0"
            }, {
                "code": "CNYNYX",
                "name": "玉溪",
                "level": "0"
            }, {
                "code": "CNYNBS",
                "name": "保山",
                "level": "0"
            }, {
                "code": "CNYNZT",
                "name": "昭通",
                "level": "0"
            }, {
                "code": "CNYNLJ",
                "name": "丽江",
                "level": "0"
            }, {
                "code": "CNYNSM",
                "name": "普洱市",
                "level": "0"
            }, {
                "code": "CNYNLC",
                "name": "临沧",
                "level": "0"
            }, {
                "code": "CNYNCX",
                "name": "楚雄",
                "level": "0"
            }, {
                "code": "CNYNHH",
                "name": "红河哈尼族彝族自治州",
                "level": "0"
            }, {
                "code": "CNYNWS",
                "name": "文山",
                "level": "0"
            }, {
                "code": "CNYNXS",
                "name": "西双版纳",
                "level": "0"
            }, {
                "code": "CNYNDL",
                "name": "大理",
                "level": "0"
            }, {
                "code": "CNYNDH",
                "name": "德宏傣族景颇族自治州",
                "level": "0"
            }, {
                "code": "CNYNNJ",
                "name": "怒江",
                "level": "0"
            }, {
                "code": "CNYNDQ",
                "name": "迪庆",
                "level": "0"
            }]
        }, {
            "code": "CNXZ",
            "name": "西藏",
            "children": [{
                "code": "CNXZLS",
                "name": "拉萨",
                "level": "0"
            }, {
                "code": "CNXZCD",
                "name": "昌都",
                "level": "0"
            }, {
                "code": "CNXZSN",
                "name": "山南",
                "level": "0"
            }, {
                "code": "CNXZRG",
                "name": "日喀则",
                "level": "0"
            }, {
                "code": "CNXZNQ",
                "name": "那曲",
                "level": "0"
            }, {
                "code": "CNXZAL",
                "name": "阿里",
                "level": "0"
            }, {
                "code": "CNXZLZ",
                "name": "林芝",
                "level": "0"
            }]
        }, {
            "code": "CNXA",
            "name": "陕西",
            "children": [{
                "code": "CNXAXA",
                "name": "西安",
                "level": "2"
            }, {
                "code": "CNXATC",
                "name": "铜川",
                "level": "0"
            }, {
                "code": "CNXABJ",
                "name": "宝鸡",
                "level": "0"
            }, {
                "code": "CNXAXY",
                "name": "咸阳",
                "level": "0"
            }, {
                "code": "CNXAWN",
                "name": "渭南",
                "level": "0"
            }, {
                "code": "CNXAYA",
                "name": "延安",
                "level": "0"
            }, {
                "code": "CNXAHZ",
                "name": "汉中",
                "level": "0"
            }, {
                "code": "CNXAYL",
                "name": "榆林",
                "level": "0"
            }, {
                "code": "CNXAAK",
                "name": "安康",
                "level": "0"
            }, {
                "code": "CNXASL",
                "name": "商洛",
                "level": "0"
            }]
        }, {
            "code": "CNGS",
            "name": "甘肃",
            "children": [{
                "code": "CNGSLZ",
                "name": "兰州",
                "level": "0"
            }, {
                "code": "CNGSJY",
                "name": "嘉峪关",
                "level": "0"
            }, {
                "code": "CNGSJC",
                "name": "金昌市",
                "level": "0"
            }, {
                "code": "CNGSBY",
                "name": "白银市",
                "level": "0"
            }, {
                "code": "CNGSTS",
                "name": "天水",
                "level": "0"
            }, {
                "code": "CNGSWW",
                "name": "武威",
                "level": "0"
            }, {
                "code": "CNGSZY",
                "name": "张掖",
                "level": "0"
            }, {
                "code": "CNGSPL",
                "name": "平凉",
                "level": "0"
            }, {
                "code": "CNGSJQ",
                "name": "酒泉",
                "level": "0"
            }, {
                "code": "CNGSQY",
                "name": "庆阳",
                "level": "0"
            }, {
                "code": "CNGSDX",
                "name": "定西",
                "level": "0"
            }, {
                "code": "CNGSLN",
                "name": "陇南",
                "level": "0"
            }, {
                "code": "CNGSLX",
                "name": "临夏回族自治州",
                "level": "0"
            }, {
                "code": "CNGSGN",
                "name": "甘南藏族自治州",
                "level": "0"
            }]
        }, {
            "code": "CNQH",
            "name": "青海",
            "children": [{
                "code": "CNQHXN",
                "name": "西宁",
                "level": "0"
            }, {
                "code": "CNQHHD",
                "name": "海东",
                "level": "0"
            }, {
                "code": "CNQHHB",
                "name": "海北",
                "level": "0"
            }, {
                "code": "CNQHHH",
                "name": "黄南",
                "level": "0"
            }, {
                "code": "CNQHHN",
                "name": "海南",
                "level": "0"
            }, {
                "code": "CNQHGL",
                "name": "果洛",
                "level": "0"
            }, {
                "code": "CNQHYS",
                "name": "玉树",
                "level": "0"
            }, {
                "code": "CNQHHX",
                "name": "海西",
                "level": "0"
            }]
        }, {
            "code": "CNNX",
            "name": "宁夏",
            "children": [{
                "code": "CNNXYC",
                "name": "银川",
                "level": "0"
            }, {
                "code": "CNNXSZ",
                "name": "石嘴山",
                "level": "0"
            }, {
                "code": "CNNXWZ",
                "name": "吴忠",
                "level": "0"
            }, {
                "code": "CNNXGY",
                "name": "固原",
                "level": "0"
            }, {
                "code": "CNNXZW",
                "name": "中卫",
                "level": "0"
            }]
        }, {
            "code": "CNXJ",
            "name": "新疆",
            "children": [{
                "code": "CNXJWL",
                "name": "乌鲁木齐",
                "level": "0"
            }, {
                "code": "CNXJKL",
                "name": "克拉玛依",
                "level": "0"
            }, {
                "code": "CNXJTL",
                "name": "吐鲁番",
                "level": "0"
            }, {
                "code": "CNXJHM",
                "name": "哈密",
                "level": "0"
            }, {
                "code": "CNXJCJ",
                "name": "昌吉",
                "level": "0"
            }, {
                "code": "CNXJBE",
                "name": "博尔塔拉蒙古自治州",
                "level": "0"
            }, {
                "code": "CNXJBY",
                "name": "巴音",
                "level": "0"
            }, {
                "code": "CNXJEK",
                "name": "阿克苏",
                "level": "0"
            }, {
                "code": "CNXJKE",
                "name": "克孜勒苏柯尔克孜自治州",
                "level": "0"
            }, {
                "code": "CNXJKS",
                "name": "喀什",
                "level": "0"
            }, {
                "code": "CNXJHT",
                "name": "和田",
                "level": "0"
            }, {
                "code": "CNXJYL",
                "name": "伊犁哈萨克自治州",
                "level": "0"
            }, {
                "code": "CNXJTC",
                "name": "塔城",
                "level": "0"
            }, {
                "code": "CNXJAL",
                "name": "阿勒泰",
                "level": "0"
            }]
        }, {
            "code": "CNHK",
            "name": "香港",
            "level": "1"
        }, {
            "code": "CNMO",
            "name": "澳门",
            "level": "1"
        }, {
            "code": "CNTW",
            "name": "台湾",
            "level": "1"
        }]
    }
}
